# =============================================================================
# FABRIC MANAGEMENT SYSTEM - USER SERVICE LOCAL DEVELOPMENT CONFIGURATION
# =============================================================================
# This profile is used for local development when running the service
# with Maven (mvn spring-boot:run) while infrastructure runs in Docker
# =============================================================================

spring:
  # ===========================================================================
  # DATABASE CONFIGURATION
  # ===========================================================================
  datasource:
    url: jdbc:postgresql://localhost:5433/fabric_management
    username: fabric_user
    password: local_dev_2024

  # ===========================================================================
  # FLYWAY CONFIGURATION
  # ===========================================================================
  flyway:
    table: flyway_schema_history_user

  # ===========================================================================
  # CACHE CONFIGURATION
  # ===========================================================================
  data:
    redis:
      host: localhost
      port: 6379
      password: local_redis_pass

  # ===========================================================================
  # KAFKA CONFIGURATION
  # ===========================================================================
  kafka:
    bootstrap-servers: localhost:9092

# =============================================================================
# SERVER CONFIGURATION
# =============================================================================
server:
  port: 8081

# =============================================================================
# SECURITY CONFIGURATION
# =============================================================================
jwt:
  secret: "EgUbMz7OOW7+57Ehxr2jUc7mFlEQPrs/XZirqOjhI4OF42Z+sW6hF7Rj9OMEjeCBBZHuzaBICuAlMtNMMZT+6A=="
  expiration: 3600000 # 1 hour
  refresh-expiration: 86400000 # 24 hours
  algorithm: HS256
  issuer: fabric-management-system
  audience: fabric-api

# =============================================================================
# EXTERNAL SERVICES CONFIGURATION
# =============================================================================
contact-service:
  url: ${CONTACT_SERVICE_URL:http://localhost:8082}

# =============================================================================
# RESILIENCE4J CONFIGURATION (Circuit Breaker)
# =============================================================================
resilience4j:
  circuitbreaker:
    instances:
      contact-service:
        # Circuit breaker opens after 50% failure rate
        failure-rate-threshold: 50
        # Minimum calls before evaluating failure rate
        minimum-number-of-calls: 5
        # Wait 10 seconds before trying again (half-open state)
        wait-duration-in-open-state: 10s
        # Allow 3 calls in half-open state to test service recovery
        permitted-number-of-calls-in-half-open-state: 3
        # Sliding window size for failure rate calculation
        sliding-window-size: 10
        # Record these exceptions as failures
        record-exceptions:
          - feign.FeignException
          - java.net.ConnectException

  timelimiter:
    instances:
      contact-service:
        # Timeout after 3 seconds
        timeout-duration: 3s

# Enable Feign with circuit breaker
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        # Connection timeout
        connect-timeout: 5000
        # Read timeout
        read-timeout: 5000

# =============================================================================
# LOGGING CONFIGURATION (More verbose for local development)
# =============================================================================
logging:
  level:
    com.fabricmanagement.user: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
