# =============================================================================
# USER SERVICE - PRODUCTION ENVIRONMENT OVERRIDES
# =============================================================================
# Contains only production-specific configuration overrides

# =============================================================================
# PRODUCTION OVERRIDES
# =============================================================================
spring:
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: validate # Strict validation in production
    show-sql: false # Disable SQL logging for performance
    properties:
      hibernate:
        show_sql: false
        format_sql: false

# =============================================================================
# PRODUCTION DATABASE OVERRIDES
# =============================================================================
spring:
  datasource:
    hikari:
      maximum-pool-size: 50 # Increased pool size for production
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

# =============================================================================
# PRODUCTION USER SERVICE OVERRIDES
# =============================================================================
user:
  profile:
    image-upload:
      max-size: 2MB # Stricter size limit for production
      storage-path: ${USER_UPLOAD_PATH:/var/app/uploads/users}
  notification:
    email:
      enabled: true # Enable email notifications in production
    sms:
      enabled: true # Enable SMS notifications in production

# =============================================================================
# PRODUCTION LOGGING
# =============================================================================
logging:
  level:
    com.fabricmanagement.user: INFO
    root: WARN
