# =============================================================================
# USER SERVICE - LOCAL ENVIRONMENT OVERRIDES
# =============================================================================
# Contains only local development-specific configuration overrides

# =============================================================================
# DEVELOPMENT OVERRIDES
# =============================================================================
spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update # Allow schema updates in local development
    show-sql: true # Enable SQL logging for debugging
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# =============================================================================
# LOCAL USER SERVICE OVERRIDES
# =============================================================================
user:
  profile:
    image-upload:
      storage-path: /tmp/uploads/users # Local temp directory for development
  notification:
    email:
      enabled: false # Disable email notifications in local development
    sms:
      enabled: false # Disable SMS notifications in local development

# =============================================================================
# DEVELOPMENT LOGGING
# =============================================================================
logging:
  level:
    com.fabricmanagement.user: DEBUG
