apiVersion: v1
kind: ConfigMap
metadata:
  name: fabric-management-config
  namespace: fabric-management
data:
  # Database Configuration
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"
  POSTGRES_DB: fabric_management

  # Redis Configuration
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"

  # Kafka Configuration
  KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092

  # Service Discovery (using exact ports from application.yml)
  AUTH_SERVICE_URL: http://auth-service:8081
  USER_SERVICE_URL: http://user-service:8082
  COMPANY_SERVICE_URL: http://company-service:8083
  CONTACT_SERVICE_URL: http://contact-service:8084

  # Spring Configuration
  SPRING_PROFILES_ACTIVE: prod

  # JVM Configuration
  JAVA_OPTS: "-Xms1024m -Xmx2048m -XX:+UseG1GC -XX:+UseStringDeduplication"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: fabric-management
data:
  init.sql: |
    -- Initialize databases for each service
    CREATE DATABASE fabric_management_auth;
    CREATE DATABASE fabric_management_user;
    CREATE DATABASE fabric_management_company;
    CREATE DATABASE fabric_management_contact;
    
    -- Create service-specific users
    CREATE USER auth_service WITH PASSWORD 'auth_service_password';
    CREATE USER user_service WITH PASSWORD 'user_service_password';
    CREATE USER company_service WITH PASSWORD 'company_service_password';
    CREATE USER contact_service WITH PASSWORD 'contact_service_password';
    
    -- Grant permissions
    GRANT ALL PRIVILEGES ON DATABASE fabric_management_auth TO auth_service;
    GRANT ALL PRIVILEGES ON DATABASE fabric_management_user TO user_service;
    GRANT ALL PRIVILEGES ON DATABASE fabric_management_company TO company_service;
    GRANT ALL PRIVILEGES ON DATABASE fabric_management_contact TO contact_service;
