services:
  postgres-user:
    image: postgres:15-alpine
    container_name: user-db
    environment:
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5433:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - fabric-network
    restart: unless-stopped

volumes:
  user_db_data:
    driver: local

networks:
  fabric-network:
    driver: bridge