# ==============================================
# FABRIC MANAGEMENT SYSTEM - DOCKER COMPOSE
# ==============================================

networks:
  fabric-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  # ==============================================
  # DATABASE SERVICES
  # ==============================================
  postgres-db:
    image: postgres:15-alpine
    container_name: fabric-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-fabric_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fabric_password}
      POSTGRES_DB: ${POSTGRES_DB:-fabric_management}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8"
    ports:
      - "${POSTGRES_DOCKER_PORT:-5433}:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/01-init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fabric-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-fabric_user} -d ${POSTGRES_DB:-fabric_management}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # ==============================================
  # CACHE & SESSION STORE
  # ==============================================
  redis:
    image: redis:7-alpine
    container_name: fabric-redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
    ports:
      - "${REDIS_DOCKER_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - fabric-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # ==============================================
  # MESSAGE BROKER
  # ==============================================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: fabric-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "${ZOOKEEPER_DOCKER_PORT:-2181}:2181"
    networks:
      - fabric-network
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: fabric-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "${KAFKA_DOCKER_PORT:-9092}:9092"
    networks:
      - fabric-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "kafka-broker-api-versions",
          "--bootstrap-server",
          "localhost:9092",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==============================================
  # MICROSERVICES (Using exact ports from application.yml)
  # ==============================================
  identity-service:
    build:
      context: . # Root directory context to access parent pom and common modules
      dockerfile: services/identity-service/Dockerfile
    container_name: fabric-identity-service
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-local}
      POSTGRES_HOST: postgres-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-fabric_management}
      POSTGRES_USER: ${POSTGRES_USER:-fabric_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fabric_password}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      JAVA_OPTS: ${JAVA_OPTS:--Xms512m -Xmx1024m -XX:+UseG1GC}
    ports:
      - "8081:8081" # identity-service port from application.yml
    networks:
      - fabric-network
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8081/api/identity/actuator/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  user-service:
    build:
      context: . # Root directory context to access parent pom and common modules
      dockerfile: services/user-service/Dockerfile
    container_name: fabric-user-service
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-local}
      POSTGRES_HOST: postgres-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-fabric_management}
      POSTGRES_USER: ${POSTGRES_USER:-fabric_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fabric_password}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      JAVA_OPTS: ${JAVA_OPTS:--Xms512m -Xmx1024m -XX:+UseG1GC}
    ports:
      - "8082:8082" # user-service port from application.yml
    networks:
      - fabric-network
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8082/api/v1/users/actuator/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  company-service:
    build:
      context: . # Root directory context to access parent pom and common modules
      dockerfile: services/company-service/Dockerfile
    container_name: fabric-company-service
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-local}
      POSTGRES_HOST: postgres-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-fabric_management}
      POSTGRES_USER: ${POSTGRES_USER:-fabric_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fabric_password}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      JAVA_OPTS: ${JAVA_OPTS:--Xms512m -Xmx1024m -XX:+UseG1GC}
    ports:
      - "8083:8083" # company-service port from application.yml
    networks:
      - fabric-network
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8083/api/v1/companies/actuator/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  contact-service:
    build:
      context: . # Root directory context to access parent pom and common modules
      dockerfile: services/contact-service/Dockerfile
    container_name: fabric-contact-service
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-local}
      POSTGRES_HOST: postgres-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-fabric_management}
      POSTGRES_USER: ${POSTGRES_USER:-fabric_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fabric_password}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      JAVA_OPTS: ${JAVA_OPTS:--Xms512m -Xmx1024m -XX:+UseG1GC}
    ports:
      - "8084:8084" # contact-service port from application.yml
    networks:
      - fabric-network
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8084/api/v1/contacts/actuator/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
