package com.fabricmanagement.offline.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import java.time.Instant;
import java.util.UUID;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Embedded offline synchronization metadata for entities created or updated from a mobile client
 * while in offline mode.
 *
 * <p>Supports Phase 11 offline operation strategies:
 *
 * <ul>
 *   <li>{@link #offlineId} — UUID assigned by the client device before syncing with the backend.
 *   <li>{@link #deviceId} — Tracks origin device of creation.
 *   <li>{@link #offlineCreatedAt} — Device-local timestamp of creation.
 *   <li>{@link #syncStatus} — Tracks resolution status of sync conflicts.
 * </ul>
 *
 * <p><b>CR-11-06 note:</b> This class is {@code @Embeddable} and used via {@code @Embedded} in
 * multiple entities (Quote, SalesOrder, TradingPartner, SampleRequest). Each entity maps to a
 * different table, so there is no column name clash. If a single entity ever needs two
 * OfflineMetadata fields, use {@code @AttributeOverride} to disambiguate column names.
 */
@Embeddable
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class OfflineMetadata {

  /** The UUID generated by the offline device for the entity before syncing. */
  @Column(name = "offline_id")
  private UUID offlineId;

  /** The unique identifier or alias of the mobile device (max 100 chars, alphanumeric). */
  @Column(name = "offline_device_id", length = 100)
  private String deviceId;

  /** The actual timestamp when the user created this record on the device. */
  @Column(name = "offline_created_at")
  private Instant offlineCreatedAt;

  /** The server timestamp indicating when this record was synchronized/merged. */
  @Column(name = "synced_at")
  private Instant syncedAt;

  /** Status of the sync action: typically PENDING when payload received, SYNCED when merged. */
  @Enumerated(EnumType.STRING)
  @Column(name = "sync_status", length = 20)
  private SyncStatus syncStatus;

  /**
   * Detailed reason if a conflict occurs (e.g. Type 1, 2, 3 or 4 conflict). CR-11-04: Using TEXT to
   * support long conflict descriptions.
   */
  @Column(name = "sync_conflict_reason", columnDefinition = "TEXT")
  private String conflictReason;

  /**
   * Initializes default metadata for an offline-originated entity that just arrived to the backend.
   */
  public static OfflineMetadata pendingSync(
      UUID offlineId, String deviceId, Instant offlineCreatedAt) {
    return OfflineMetadata.builder()
        .offlineId(offlineId)
        .deviceId(deviceId)
        .offlineCreatedAt(offlineCreatedAt)
        .syncStatus(SyncStatus.PENDING)
        .build();
  }

  /**
   * Marks this metadata as successfully synced.
   *
   * <p>CR-11-01 fix: accepts explicit {@code now} parameter for testability instead of calling
   * {@code Instant.now()} internally.
   *
   * @param now the server timestamp to record as sync time
   * @throws IllegalStateException if current status cannot transition to SYNCED
   */
  public void markSynced(Instant now) {
    validateTransition(SyncStatus.SYNCED);
    this.syncStatus = SyncStatus.SYNCED;
    this.syncedAt = now;
    this.conflictReason = null;
  }

  /**
   * Marks this metadata as conflicted.
   *
   * @param reason detailed description of the conflict (e.g. "TİP 1: Aynı müşteriye duplicate
   *     Quote")
   * @throws IllegalStateException if current status cannot transition to CONFLICT
   */
  public void markConflicted(String reason) {
    validateTransition(SyncStatus.CONFLICT);
    this.syncStatus = SyncStatus.CONFLICT;
    this.conflictReason = reason;
  }

  /**
   * Marks this metadata as resolved by a manager after a conflict.
   *
   * @throws IllegalStateException if current status cannot transition to RESOLVED
   */
  public void markResolved() {
    validateTransition(SyncStatus.RESOLVED);
    this.syncStatus = SyncStatus.RESOLVED;
  }

  /**
   * Validates that the current status can transition to the target status.
   *
   * @throws IllegalStateException if the transition is not allowed
   */
  private void validateTransition(SyncStatus target) {
    if (syncStatus != null && !syncStatus.canTransitionTo(target)) {
      throw new IllegalStateException(
          String.format(
              "Invalid sync status transition: %s → %s (allowed: %s)",
              syncStatus, target, syncStatus.allowedTransitions()));
    }
  }
}
