# =============================================================================
# AUTH SERVICE - PRODUCTION ENVIRONMENT OVERRIDES
# =============================================================================
# Contains only production-specific configuration overrides

# =============================================================================
# PRODUCTION OVERRIDES
# =============================================================================
spring:
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: validate # Strict validation in production
    show-sql: false # Disable SQL logging for performance
    properties:
      hibernate:
        show_sql: false
        format_sql: false

# =============================================================================
# PRODUCTION DATABASE OVERRIDES
# =============================================================================
spring:
  datasource:
    hikari:
      maximum-pool-size: 50 # Increased pool size for production
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

# =============================================================================
# PRODUCTION SECURITY OVERRIDES
# =============================================================================
security:
  password:
    encoder: bcrypt
    strength: 12 # Higher strength for production

jwt:
  expiration: 3600000 # 1 hour (shorter for production security)
  refresh-expiration: 86400000 # 24 hours

# =============================================================================
# PRODUCTION AUTH OVERRIDES
# =============================================================================
auth:
  max-login-attempts: 3 # Stricter in production
  lockout-duration: 900000 # 15 minutes
  password-reset-expiration: 1800000 # 30 minutes (shorter for security)

# =============================================================================
# PRODUCTION LOGGING
# =============================================================================
logging:
  level:
    com.fabricmanagement.auth: INFO
    org.springframework.security: WARN
    root: WARN
