# =============================================================================
# FABRIC MANAGEMENT SYSTEM - AUTH SERVICE CONFIGURATION
# =============================================================================
# Service-specific configuration for authentication and authorization service

# =============================================================================
# APPLICATION CONFIGURATION
# =============================================================================
spring:
  application:
    name: auth-service
  profiles:
    active: local

# =============================================================================
# SERVER CONFIGURATION
# =============================================================================
server:
  port: 8081
  servlet:
    context-path: /api/v1/auth

# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DB:fabric_management}
    username: ${POSTGRES_USER:fabric_user}
    password: ${POSTGRES_PASSWORD:fabric_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

# =============================================================================
# SECURITY CONFIGURATION
# =============================================================================
jwt:
  secret: ${JWT_SECRET:defaultSecretKey123456789012345678901234567890}
  expiration: 86400000 # 24 hours
  refresh-expiration: 604800000 # 7 days

security:
  password:
    encoder: bcrypt
  oauth2:
    enabled: false

# =============================================================================
# SERVICE-SPECIFIC CONFIGURATION
# =============================================================================
auth:
  max-login-attempts: 5
  lockout-duration: 300000 # 5 minutes
  password-reset-expiration: 3600000 # 1 hour
  email-verification-expiration: 86400000 # 24 hours
