# =============================================================================
# AUTH SERVICE - LOCAL ENVIRONMENT OVERRIDES
# =============================================================================
# Contains only local development-specific configuration overrides

# =============================================================================
# DEVELOPMENT OVERRIDES
# =============================================================================
spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update # Allow schema updates in local development
    show-sql: true # Enable SQL logging for debugging
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# =============================================================================
# LOCAL SECURITY OVERRIDES
# =============================================================================
security:
  password:
    encoder: bcrypt
    strength: 10 # Lower strength for faster local development

# =============================================================================
# LOCAL AUTH OVERRIDES
# =============================================================================
auth:
  max-login-attempts: 10 # More lenient for development
  lockout-duration: 60000 # 1 minute (shorter for development)

# =============================================================================
# DEVELOPMENT LOGGING
# =============================================================================
logging:
  level:
    com.fabricmanagement.auth: DEBUG
    org.springframework.security: DEBUG
