spring:
  application:
    name: fabric-management-system

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=300s

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Management & Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

# Application Info
info:
  app:
    name: ${spring.application.name}
    description: Modular Monolith Fabric Management System
    version: 1.0.0
    architecture: Modular Monolith
    encoding: ${project.build.sourceEncoding:UTF-8}
    java:
      version: ${java.version:21}

# Logging
logging:
  level:
    root: INFO
    com.fabricmanagement: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application Properties
application:
  name: Fabric Management System
  version: 1.0.0
  architecture: modular-monolith

  # JWT Configuration
  jwt:
    secret: ${JWT_SECRET:YourSecretKeyMustBe256BitsLongForHS256AlgorithmToWorkProperly}
    expiration: ${JWT_EXPIRATION:900000} # 15 minutes
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days

  # Tenant Configuration
  tenant:
    default-tenant-id: ${DEFAULT_TENANT_ID:00000000-0000-0000-0000-000000000000}

  # Verification Configuration
  verification:
    code-length: 6
    code-expiry-minutes: 10
    max-attempts: 3
    resend-delay-seconds: 60

  # Policy Configuration
  policy:
    cache-ttl-seconds: 300 # 5 minutes
    default-decision: DENY
    evaluation-timeout-ms: 1000

  # Event Configuration
  events:
    async-enabled: true
    outbox-enabled: true
    outbox-batch-size: 100
    outbox-poll-interval-ms: 5000

# OpenAPI / Swagger
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: false
