# =============================================================================
# FABRIC MANAGEMENT SYSTEM - CONTACT SERVICE DOCKER CONFIGURATION
# =============================================================================
# Docker environment configuration for contact management service

# =============================================================================
# APPLICATION CONFIGURATION
# =============================================================================
spring:
  application:
    name: contact-service

  # ===========================================================================
  # DATABASE CONFIGURATION
  # ===========================================================================
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:fabric_management}
    username: ${POSTGRES_USER:fabric_user}
    password: ${POSTGRES_PASSWORD:fabric_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE:10}
      minimum-idle: ${DB_POOL_MIN_IDLE:2}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${DB_IDLE_TIMEOUT:600000}
      max-lifetime: ${DB_MAX_LIFETIME:1800000}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    show-sql: false
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    table: contact_flyway_schema_history # ✅ Separate history table per service
    baseline-on-migrate: true # ✅ REQUIRED: init.sql creates extensions/functions first
    baseline-version: 0 # ✅ Baseline at v0, so V1 migrations run
    validate-on-migrate: true
    clean-disabled: true
    repair-on-migrate: false

  # ===========================================================================
  # CACHE CONFIGURATION
  # ===========================================================================
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_CONNECTION_TIMEOUT:2000ms}
      connect-timeout: ${REDIS_COMMAND_TIMEOUT:3000ms}
      lettuce:
        pool:
          max-active: ${REDIS_POOL_MAX_ACTIVE:8}
          max-idle: ${REDIS_POOL_MAX_IDLE:8}
          min-idle: ${REDIS_POOL_MIN_IDLE:2}

  cache:
    type: redis
    redis:
      time-to-live: ${CACHE_TTL:300000} # 5 minutes

  # ===========================================================================
  # KAFKA CONFIGURATION
  # ===========================================================================
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9093}
    producer:
      client-id: ${spring.application.name}-producer-${HOSTNAME:${random.uuid}}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: ${KAFKA_PRODUCER_ACKS:all}
      retries: ${KAFKA_PRODUCER_RETRIES:3}
      enable-idempotence: ${KAFKA_PRODUCER_IDEMPOTENCE:true}
      max-in-flight-requests-per-connection: ${KAFKA_PRODUCER_MAX_IN_FLIGHT:1}
      batch-size: ${KAFKA_PRODUCER_BATCH_SIZE:16384}
      linger-ms: ${KAFKA_PRODUCER_LINGER_MS:5}
      buffer-memory: ${KAFKA_PRODUCER_BUFFER_MEMORY:33554432}
    consumer:
      client-id: ${spring.application.name}-consumer-${HOSTNAME:${random.uuid}}
      # ErrorHandlingDeserializer wrapper for graceful error handling
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: ${KAFKA_CONSUMER_GROUP_ID:contact-service-group}
      auto-offset-reset: ${KAFKA_CONSUMER_AUTO_OFFSET_RESET:earliest}
      enable-auto-commit: ${KAFKA_CONSUMER_ENABLE_AUTO_COMMIT:false}
      heartbeat-interval: ${KAFKA_CONSUMER_HEARTBEAT_INTERVAL:3000}
      properties:
        # Trust all com.fabricmanagement.* packages (including sub-packages)
        spring.json.trusted.packages: ${KAFKA_TRUSTED_PACKAGES:com.fabricmanagement.*,java.util,java.lang}
        # Delegate deserializers (actual deserializers wrapped by ErrorHandlingDeserializer)
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        allow.auto.create.topics: ${KAFKA_AUTO_CREATE_TOPICS:true}
        jmx.prefix: contact-service
        session.timeout.ms: ${KAFKA_CONSUMER_SESSION_TIMEOUT:30000}
        connections.max.idle.ms: ${KAFKA_CONSUMER_MAX_IDLE:540000}

# =============================================================================
# SERVER CONFIGURATION
# =============================================================================
server:
  port: ${CONTACT_SERVICE_PORT:8082}
  # Note: No context-path - Gateway handles API versioning and routing
  # Gateway strips /api/v1/contacts prefix before forwarding to this service

# Kafka Topics Configuration
kafka:
  topics:
    email-notifications: email-notifications
    sms-notifications: sms-notifications
    contact-events: contact-events

# Notification Configuration
notification:
  enabled: ${NOTIFICATION_ENABLED:true}

# =============================================================================
# MANAGEMENT & MONITORING
# =============================================================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# =============================================================================
# OPENAPI/SWAGGER CONFIGURATION
# =============================================================================
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
logging:
  level:
    com.fabricmanagement.contact: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  # File logging disabled in Docker - logs should go to stdout/stderr
  # Docker will handle log collection and rotation
  # file:
  #   name: logs/contact-service.log
