# =============================================================================
# FABRIC MANAGEMENT SYSTEM - CONTACT SERVICE LOCAL DEVELOPMENT CONFIGURATION
# =============================================================================
# This profile is used for local development when running the service
# with Maven (mvn spring-boot:run) while infrastructure runs in Docker
# =============================================================================

spring:
  # ===========================================================================
  # DATABASE CONFIGURATION
  # ===========================================================================
  datasource:
    url: jdbc:postgresql://localhost:5433/fabric_management
    username: fabric_user
    password: local_dev_2024

  # ===========================================================================
  # FLYWAY CONFIGURATION
  # ===========================================================================
  flyway:
    table: flyway_schema_history_contact

  # ===========================================================================
  # CACHE CONFIGURATION
  # ===========================================================================
  data:
    redis:
      host: localhost
      port: 6379
      password: local_redis_pass

  # ===========================================================================
  # KAFKA CONFIGURATION
  # ===========================================================================
  kafka:
    bootstrap-servers: localhost:9092

# =============================================================================
# SERVER CONFIGURATION
# =============================================================================
server:
  port: 8082

# =============================================================================
# SECURITY CONFIGURATION
# =============================================================================
jwt:
  secret: "EgUbMz7OOW7+57Ehxr2jUc7mFlEQPrs/XZirqOjhI4OF42Z+sW6hF7Rj9OMEjeCBBZHuzaBICuAlMtNMMZT+6A=="
  expiration: 3600000 # 1 hour
  refresh-expiration: 86400000 # 24 hours
  algorithm: HS256
  issuer: fabric-management-system
  audience: fabric-api

# =============================================================================
# LOGGING CONFIGURATION (More verbose for local development)
# =============================================================================
logging:
  level:
    com.fabricmanagement.contact: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
