# =============================================================================
# CONTACT SERVICE - PRODUCTION ENVIRONMENT OVERRIDES
# =============================================================================
# Contains only production-specific configuration overrides

# =============================================================================
# PRODUCTION OVERRIDES
# =============================================================================
spring:
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: validate # Strict validation in production
    show-sql: false # Disable SQL logging for performance
    properties:
      hibernate:
        show_sql: false
        format_sql: false

# =============================================================================
# PRODUCTION DATABASE OVERRIDES
# =============================================================================
spring:
  datasource:
    hikari:
      maximum-pool-size: 50 # Increased pool size for production
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

# =============================================================================
# PRODUCTION CONTACT SERVICE OVERRIDES
# =============================================================================
contact:
  communication:
    email:
      enabled: true # Enable email in production
      provider: ${EMAIL_PROVIDER:sendgrid}
    sms:
      enabled: true # Enable SMS in production
      provider: ${SMS_PROVIDER:twilio}
  import:
    batch-size: 5000 # Larger batch size for production performance
    max-file-size: 10MB # Stricter file size for production
  export:
    max-records: 50000 # Higher limit for production

# =============================================================================
# PRODUCTION LOGGING
# =============================================================================
logging:
  level:
    com.fabricmanagement.contact: INFO
    root: WARN
