version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: fabric_db
      POSTGRES_USER: fabric_user
      POSTGRES_PASSWORD: fabric_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fabric-network

  # Identity Provider
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: fabric_user
      KC_DB_PASSWORD: fabric_pass
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - fabric-network
    command: start-dev

  # Message Broker
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: fabric
      RABBITMQ_DEFAULT_PASS: fabric123
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - fabric-network

  # Monitoring
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - fabric-network

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - fabric-network

  # Distributed Tracing
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    networks:
      - fabric-network

  # Service Discovery
  eureka-server:
    build: ./infrastructure/service-discovery
    ports:
      - "8761:8761"
    networks:
      - fabric-network

  # Config Server
  config-server:
    build: ./infrastructure/config-server
    ports:
      - "8888:8888"
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - fabric-network

  # API Gateway
  api-gateway:
    build: ./infrastructure/api-gateway
    ports:
      - "8000:8000"
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
    depends_on:
      - eureka-server
      - config-server
    networks:
      - fabric-network

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:

networks:
  fabric-network:
    driver: bridge