package com.fabricmanagement.production.security;

import com.fabricmanagement.common.infrastructure.security.AuthenticatedUserContext;
import java.util.Map;
import java.util.Set;
import lombok.extern.slf4j.Slf4j;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Service;

/**
 * Production module authorization service — evaluates <em>role + department</em> together.
 *
 * <h2>Architecture: Generic Role + Department Context (Yol A)</h2>
 *
 * <p>Spring Security's built-in {@code hasRole()} only checks the role. This service adds the
 * second dimension: <em>which department does the user belong to?</em>
 *
 * <p>Designed to be invoked from {@code @PreAuthorize} SpEL expressions:
 *
 * <pre>
 * // Fiber masterdata — write (create / update / deactivate)
 * {@code @PreAuthorize("@productionAccessService.hasPermission(authentication, 'FIBER', 'WRITE')")}
 *
 * // Batch execution — reserve / release / consume
 * {@code @PreAuthorize("@productionAccessService.hasPermission(authentication, 'BATCH', 'WRITE')")}
 * </pre>
 *
 * <h2>Permission Matrix</h2>
 *
 * <pre>
 * ┌────────────────────────────┬───────────────────┬──────────────┬──────────────┬──────────────────────┐
 * │ Role / Department          │ FIBER / MATERIAL  │ BATCH        │ QUALITY_TEST │ WAREHOUSE_LOCATION   │
 * ├────────────────────────────┼───────────────────┼──────────────┼──────────────┼──────────────────────┤
 * │ ADMIN (any dept)           │ READ + WRITE      │ READ + WRITE │ READ + WRITE │ READ + WRITE         │
 * │ MANAGER + R&D/Prod.Dev.    │ READ + WRITE      │ READ + WRITE │ READ + WRITE │ READ only            │
 * │ MANAGER + Prod.Planning    │ READ + WRITE      │ READ + WRITE │ READ only    │ READ + WRITE         │
 * │ MANAGER + Fiber&RawMat.    │ READ + WRITE      │ READ + WRITE │ READ + WRITE │ READ only            │
 * │ MANAGER + QualityControl   │ READ only         │ READ + WRITE │ READ + WRITE │ READ only            │
 * │ MANAGER + Warehouse        │ READ only         │ READ + WRITE │ READ only    │ READ + WRITE         │
 * │ MANAGER + other prod. dept │ READ only         │ READ + WRITE │ READ only    │ READ only            │
 * │ SUPERVISOR + QC/R&D/Fiber  │ READ only         │ READ + WRITE │ READ + WRITE │ READ only            │
 * │ SUPERVISOR + Warehouse     │ READ only         │ READ + WRITE │ READ only    │ READ + WRITE         │
 * │ SUPERVISOR + other prod.   │ READ only         │ READ + WRITE │ READ only    │ READ only            │
 * │ WORKER / VIEWER + any dept │ READ only         │ READ only    │ READ only    │ READ only            │
 * └────────────────────────────┴───────────────────┴──────────────┴──────────────┴──────────────────────┘
 * </pre>
 *
 * <h2>Department Codes</h2>
 *
 * <p>Codes are generated by {@code TenantSeedService.generateDepartmentCode()} (upper-case,
 * alphanumeric only):
 *
 * <ul>
 *   <li>{@code RDPRODUCTDEVELOPMENT} — R&D / Product Development
 *   <li>{@code PRODUCTIONPLANNING} — Production Planning
 *   <li>{@code FIBERRAWMATERIAL} — Fiber & Raw Material
 *   <li>{@code YARNPRODUCTION} — Yarn Production
 *   <li>{@code WEAVINGKNITTING} — Weaving & Knitting
 *   <li>{@code DYEINGFINISHING} — Dyeing & Finishing
 *   <li>{@code QUALITYCONTROL} — Quality Control
 *   <li>{@code WAREHOUSE} — Warehouse
 * </ul>
 */
@Service("productionAccessService")
@Slf4j
public class ProductionAccessService {

  // ── Supported modules ──────────────────────────────────────────────────────

  /** Fiber masterdata catalog ({@code /api/production/fibers}). */
  public static final String MODULE_FIBER = "FIBER";

  /** Material masterdata catalog ({@code /api/production/materials}). */
  public static final String MODULE_MATERIAL = "MATERIAL";

  /** Fiber batch execution — lot / inventory ({@code /api/production/batches/fiber}). */
  public static final String MODULE_BATCH = "BATCH";

  /** Quality test results ({@code /api/production/quality/fiber-tests}). */
  public static final String MODULE_QUALITY_TEST = "QUALITY_TEST";

  /** Warehouse location masterdata ({@code /api/production/warehouse-locations}). */
  public static final String MODULE_WAREHOUSE_LOCATION = "WAREHOUSE_LOCATION";

  // ── Supported actions ──────────────────────────────────────────────────────

  public static final String ACTION_READ = "READ";
  public static final String ACTION_WRITE = "WRITE";

  // ── Role codes (must match DB role_code values in R__002) ──────────────────

  private static final Set<String> SUPER_ROLES = Set.of("ADMIN", "PLATFORM_ADMIN");
  private static final Set<String> MANAGEMENT_ROLES = Set.of("ADMIN", "PLATFORM_ADMIN", "MANAGER");
  private static final Set<String> OPERATIONAL_ROLES =
      Set.of("ADMIN", "PLATFORM_ADMIN", "MANAGER", "SUPERVISOR");

  // ── Department codes (TenantSeedService.generateDepartmentCode output) ─────

  /**
   * Departments that own fiber <em>masterdata</em>: entitled to WRITE on FIBER and MATERIAL
   * modules.
   */
  private static final Set<String> FIBER_MASTERDATA_WRITE_DEPARTMENTS =
      Set.of("RDPRODUCTDEVELOPMENT", "PRODUCTIONPLANNING", "FIBERRAWMATERIAL");

  /** All production-adjacent departments: entitled to READ/WRITE on BATCH (execution layer). */
  private static final Set<String> BATCH_WRITE_DEPARTMENTS =
      Set.of(
          "RDPRODUCTDEVELOPMENT",
          "PRODUCTIONPLANNING",
          "FIBERRAWMATERIAL",
          "YARNPRODUCTION",
          "WEAVINGKNITTING",
          "DYEINGFINISHING",
          "QUALITYCONTROL",
          "WAREHOUSE");

  /**
   * Quality test WRITE departments: QC owns test results, but R&D and incoming inspection (Fiber &
   * Raw Material) can also record tests.
   */
  private static final Set<String> QUALITY_TEST_WRITE_DEPARTMENTS =
      Set.of("QUALITYCONTROL", "RDPRODUCTDEVELOPMENT", "FIBERRAWMATERIAL");

  /**
   * Warehouse location WRITE departments: the Warehouse team owns the physical location catalog;
   * Production Planning also needs to manage locations for planning purposes.
   */
  private static final Set<String> WAREHOUSE_LOCATION_WRITE_DEPARTMENTS =
      Set.of("WAREHOUSE", "PRODUCTIONPLANNING");

  /**
   * READ is open to any production-related department (includes QC and Warehouse who consume fiber
   * data).
   */
  private static final Set<String> ALL_PRODUCTION_READ_DEPARTMENTS =
      Set.of(
          "RDPRODUCTDEVELOPMENT",
          "PRODUCTIONPLANNING",
          "FIBERRAWMATERIAL",
          "YARNPRODUCTION",
          "WEAVINGKNITTING",
          "DYEINGFINISHING",
          "QUALITYCONTROL",
          "WAREHOUSE",
          "PROCUREMENTSUPPLY");

  // ── Write department mapping per module ────────────────────────────────────

  private static final Map<String, Set<String>> WRITE_DEPARTMENTS_BY_MODULE =
      Map.of(
          MODULE_FIBER, FIBER_MASTERDATA_WRITE_DEPARTMENTS,
          MODULE_MATERIAL, FIBER_MASTERDATA_WRITE_DEPARTMENTS,
          MODULE_BATCH, BATCH_WRITE_DEPARTMENTS,
          MODULE_QUALITY_TEST, QUALITY_TEST_WRITE_DEPARTMENTS,
          MODULE_WAREHOUSE_LOCATION, WAREHOUSE_LOCATION_WRITE_DEPARTMENTS);

  /** All known modules — used to reject unknown module names early. */
  private static final Set<String> KNOWN_MODULES =
      Set.of(
          MODULE_FIBER,
          MODULE_MATERIAL,
          MODULE_BATCH,
          MODULE_QUALITY_TEST,
          MODULE_WAREHOUSE_LOCATION);

  // ── Public API (SpEL entry point) ──────────────────────────────────────────

  /**
   * Evaluate whether the authenticated user is allowed to perform {@code action} on {@code module}.
   *
   * <p>Designed for use in {@code @PreAuthorize} SpEL:
   *
   * <pre>
   * {@code @PreAuthorize("@productionAccessService.hasPermission(authentication, 'FIBER', 'WRITE')")}
   * </pre>
   *
   * @param authentication current Spring Security Authentication (injected by SpEL)
   * @param module one of {@link #MODULE_FIBER}, {@link #MODULE_MATERIAL}, {@link #MODULE_BATCH}
   * @param action one of {@link #ACTION_READ}, {@link #ACTION_WRITE}
   * @return {@code true} if access is granted
   */
  public boolean hasPermission(Authentication authentication, String module, String action) {
    if (authentication == null || !authentication.isAuthenticated()) {
      log.debug("hasPermission denied: no valid authentication");
      return false;
    }

    if (module == null || action == null) {
      log.warn(
          "hasPermission denied: module or action is null (module={}, action={})", module, action);
      return false;
    }

    String normalizedModule = module.toUpperCase();
    String normalizedAction = action.toUpperCase();

    if (!KNOWN_MODULES.contains(normalizedModule)) {
      log.warn("hasPermission denied: unknown module '{}'", module);
      return false;
    }

    AuthenticatedUserContext ctx = extractContext(authentication);
    if (ctx == null) {
      log.warn(
          "AuthenticatedUserContext not set on Authentication; falling back to role-only check");
      return fallbackRoleOnlyCheck(authentication, normalizedAction);
    }

    boolean granted = evaluate(ctx, normalizedModule, normalizedAction);
    log.debug(
        "hasPermission: userId={}, role={}, depts={}, module={}, action={} → {}",
        ctx.userId(),
        ctx.roleCode(),
        ctx.departmentCodes(),
        normalizedModule,
        normalizedAction,
        granted);
    return granted;
  }

  // ── Internal evaluation ────────────────────────────────────────────────────

  private boolean evaluate(AuthenticatedUserContext ctx, String module, String action) {
    String role = ctx.roleCode();

    // ADMIN / PLATFORM_ADMIN bypass all department checks
    if (role != null && SUPER_ROLES.contains(role)) {
      return true;
    }

    return switch (action) {
      case ACTION_READ -> evaluateRead(ctx, module);
      case ACTION_WRITE -> evaluateWrite(ctx, module);
      default -> {
        log.warn("Unknown action '{}' requested for module '{}'", action, module);
        yield false;
      }
    };
  }

  /**
   * READ rules (module is already validated and normalized by caller):
   *
   * <ul>
   *   <li>MANAGER / SUPERVISOR — read all known production modules (they need full visibility)
   *   <li>WORKER / VIEWER — read only if assigned to a production-related department
   * </ul>
   */
  private boolean evaluateRead(AuthenticatedUserContext ctx, String module) {
    String role = ctx.roleCode();
    if (role != null && OPERATIONAL_ROLES.contains(role)) {
      return true;
    }
    return ctx.isInAnyDepartment(ALL_PRODUCTION_READ_DEPARTMENTS);
  }

  /**
   * WRITE rules (module is already validated and normalized by caller):
   *
   * <ul>
   *   <li>FIBER / MATERIAL — MANAGER + fiber masterdata department
   *   <li>BATCH — MANAGER or SUPERVISOR + production-adjacent department
   *   <li>QUALITY_TEST — MANAGER or SUPERVISOR + QC / R&D / Fiber dept
   * </ul>
   */
  private boolean evaluateWrite(AuthenticatedUserContext ctx, String module) {
    Set<String> authorizedDepts = WRITE_DEPARTMENTS_BY_MODULE.getOrDefault(module, Set.of());

    String role = ctx.roleCode();

    if ("MANAGER".equals(role)) {
      return ctx.isInAnyDepartment(authorizedDepts);
    }

    if ("SUPERVISOR".equals(role)
        && (MODULE_BATCH.equals(module)
            || MODULE_QUALITY_TEST.equals(module)
            || MODULE_WAREHOUSE_LOCATION.equals(module))) {
      return ctx.isInAnyDepartment(authorizedDepts);
    }

    return false;
  }

  // ── Helpers ────────────────────────────────────────────────────────────────

  private AuthenticatedUserContext extractContext(Authentication authentication) {
    if (authentication.getDetails() instanceof AuthenticatedUserContext ctx) {
      return ctx;
    }
    return null;
  }

  /**
   * Safety net: if {@link AuthenticatedUserContext} was not set (e.g. test context or legacy path)
   * fall back to checking Spring Security authorities only — no department enforcement.
   */
  private boolean fallbackRoleOnlyCheck(Authentication authentication, String action) {
    if (ACTION_READ.equals(action)) {
      return authentication.isAuthenticated();
    }
    return authentication.getAuthorities().stream()
        .anyMatch(a -> MANAGEMENT_ROLES.contains(a.getAuthority().replace("ROLE_", "")));
  }
}
