package com.fabricmanagement.sales.quote.api;

import com.fabricmanagement.offline.domain.OfflineMetadata;
import com.fabricmanagement.sales.quote.domain.Quote;
import jakarta.validation.constraints.FutureOrPresent;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;
import lombok.Data;

/**
 * Request body for creating a new Quote. Keeps API surface clean — internal fields (tenantId,
 * revisionNumber, status) are set by the service layer.
 *
 * <p>When a Quote is created offline on a mobile device, the client must set {@link #offlineId},
 * {@link #deviceId}, and {@link #offlineCreatedAt} so the backend can track sync status and detect
 * conflicts.
 */
@Data
public class QuoteCreateRequest {

  @NotNull(message = "Customer ID is required")
  private UUID customerId;

  @NotNull(message = "Assigned salesperson ID is required")
  private UUID assignedToId;

  @NotBlank(message = "Module type is required")
  private String moduleType;

  @NotBlank(message = "Quote number is required")
  private String quoteNumber;

  /**
   * Estimated unit cost pulled from Phase 4 CostCalculation. Optional at draft creation — can be
   * added later by linking to a CostCalculation record.
   */
  private BigDecimal estimatedUnitCost;

  @NotBlank(message = "Currency is required")
  @Pattern(regexp = "^[A-Z]{3}$", message = "Currency must be a 3-letter ISO code")
  private String currency;

  @NotNull(message = "Valid-until date is required")
  @FutureOrPresent(message = "Valid-until date must be today or in the future")
  private LocalDate validUntil;

  @Size(max = 50, message = "Payment terms must be 50 characters or less")
  private String paymentTerms;

  @Min(value = 0, message = "Lead time days must be zero or greater")
  @Max(value = 3650, message = "Lead time days must be 3650 or less")
  private Integer leadTimeDays;

  @Size(max = 2000, message = "Notes must be 2000 characters or less")
  private String notes;

  // ── Offline Sync Fields ──────────────────────────────────────────────────

  /**
   * CR-11-02: UUID generated by the mobile device for this Quote before syncing. Required for
   * idempotent sync and conflict resolution.
   */
  private UUID offlineId;

  /**
   * CR-11-12: Device identifier, validated for length and safe characters. Populated only when
   * quote was created offline on a mobile device.
   */
  @Size(max = 100, message = "Device ID must be 100 characters or less")
  @Pattern(
      regexp = "^[a-zA-Z0-9_\\-.:]*$",
      message =
          "Device ID can only contain alphanumeric characters, underscores, hyphens, dots, and colons")
  private String deviceId;

  /**
   * CR-11-02: The device-local timestamp when this Quote was created offline. Required for TYPE 2
   * conflict detection (PriceList change comparison).
   */
  private Instant offlineCreatedAt;

  /** Maps this request to a transient Quote entity for service layer processing. */
  public Quote toQuote() {
    Quote q = new Quote();
    q.setCustomerId(customerId);
    q.setAssignedToId(assignedToId);
    q.setModuleType(moduleType);
    q.setQuoteNumber(quoteNumber);
    q.setEstimatedUnitCost(estimatedUnitCost);
    q.setCurrency(currency);
    q.setValidUntil(validUntil);
    q.setPaymentTerms(paymentTerms);
    q.setLeadTimeDays(leadTimeDays);
    q.setNotes(notes);
    if (offlineId != null || deviceId != null) {
      q.setOfflineMetadata(OfflineMetadata.pendingSync(offlineId, deviceId, offlineCreatedAt));
    }
    return q;
  }
}
