apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-service
  namespace: fabric-management
  labels:
    app: company-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: company-service
  template:
    metadata:
      labels:
        app: company-service
        version: v1
    spec:
      serviceAccountName: fabric-service-account
      containers:
      - name: company-service
        image: fabric-management/company-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8083
          name: http
        - containerPort: 9083
          name: management
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: fabric-config
              key: SPRING_PROFILES_ACTIVE
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: fabric-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: fabric-config
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: fabric-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: fabric-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fabric-secrets
              key: COMPANY_DB_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: fabric-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: fabric-config
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fabric-secrets
              key: REDIS_PASSWORD
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: fabric-config
              key: AUTH_SERVICE_URL
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: fabric-config
              key: USER_SERVICE_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 9083
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 9083
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: company-service
  namespace: fabric-management
  labels:
    app: company-service
spec:
  selector:
    app: company-service
  ports:
  - name: http
    port: 8083
    targetPort: 8083
  - name: management
    port: 9083
    targetPort: 9083
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: company-service-hpa
  namespace: fabric-management
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: company-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

