apiVersion: apps/v1
kind: Deployment
metadata:
  name: logistics-service
  namespace: fabric-management
  labels:
    app: logistics-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logistics-service
  template:
    metadata:
      labels:
        app: logistics-service
        version: v1
    spec:
      containers:
        - name: logistics-service
          image: fabric-management/logistics-service:latest
          ports:
            - containerPort: 8095
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: POSTGRES_HOST
              value: "postgres-logistics"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "logistics_db"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: logistics-service-secrets
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logistics-service-secrets
                  key: postgres-password
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: "guest"
            - name: RABBITMQ_PASSWORD
              value: "guest"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: IDENTITY_SERVICE_URL
              value: "http://identity-service:8081"
            - name: CONTACT_SERVICE_URL
              value: "http://contact-service:8083"
            - name: COMPANY_SERVICE_URL
              value: "http://company-service:8084"
            - name: ORDER_SERVICE_URL
              value: "http://order-service:8094"
            - name: PRODUCTION_SERVICE_URL
              value: "http://production-service:8096"
            - name: MAPS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: logistics-service-secrets
                  key: maps-api-key
            - name: TRACKING_API_KEY
              valueFrom:
                secretKeyRef:
                  name: logistics-service-secrets
                  key: tracking-api-key
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8095
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8095
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: logistics-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: logistics-service
  namespace: fabric-management
  labels:
    app: logistics-service
spec:
  selector:
    app: logistics-service
  ports:
    - port: 8095
      targetPort: 8095
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logistics-service-config
  namespace: fabric-management
data:
  application.yml: |
    server:
      port: 8095

    spring:
      application:
        name: logistics-service
      datasource:
        url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
      redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
        password: ""
        database: 0
      rabbitmq:
        host: ${RABBITMQ_HOST}
        port: ${RABBITMQ_PORT}
        username: ${RABBITMQ_USERNAME}
        password: ${RABBITMQ_PASSWORD}
        virtual-host: /

    eureka:
      client:
        service-url:
          defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
        register-with-eureka: true
        fetch-registry: true
      instance:
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 30
        lease-expiration-duration-in-seconds: 90

    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          show-details: always
      metrics:
        export:
          prometheus:
            enabled: true

    logging:
      level:
        com.fabricmanagement.logistics: INFO
        org.springframework.web: INFO
        org.hibernate.SQL: WARN
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
      file:
        name: /app/logs/logistics-service.log

    # Service URLs
    services:
      identity:
        url: ${IDENTITY_SERVICE_URL}
      contact:
        url: ${CONTACT_SERVICE_URL}
      company:
        url: ${COMPANY_SERVICE_URL}
      order:
        url: ${ORDER_SERVICE_URL}
      production:
        url: ${PRODUCTION_SERVICE_URL}

    # External APIs
    external:
      maps:
        api-key: ${MAPS_API_KEY}
        base-url: "https://maps.googleapis.com/maps/api"
      tracking:
        api-key: ${TRACKING_API_KEY}
        base-url: "https://api.tracking.com"

    # Logistics Configuration
    logistics:
      route-optimization:
        enabled: true
        algorithm: "PRIORITY_BASED"
        buffer-time: 30
      tracking:
        update-interval: 300
        max-retries: 3
      delivery:
        default-time-window: "09:00-17:00"
        max-packages-per-route: 50
---
apiVersion: v1
kind: Secret
metadata:
  name: logistics-service-secrets
  namespace: fabric-management
type: Opaque
data:
  postgres-username: bG9naXN0aWNzX3VzZXI= # logistics_user
  postgres-password: bG9naXN0aWNzX3Bhc3M= # logistics_pass
  maps-api-key: eW91ci1tYXBzLWFwaS1rZXk= # your-maps-api-key
  tracking-api-key: eW91ci10cmFja2luZy1hcGkta2V5 # your-tracking-api-key
