# =============================================================================
# FABRIC MANAGEMENT SYSTEM - COMMON CORE CONFIGURATION
# =============================================================================
# This file contains shared configuration properties inherited by all services
# Environment-specific overrides should be placed in service-specific files

# =============================================================================
# APPLICATION CONFIGURATION
# =============================================================================
spring:
  application:
    name: fabric-management-common-core
  profiles:
    active: local

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
logging:
  level:
    root: INFO
    com.fabricmanagement: DEBUG
    org.springframework: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/${spring.application.name}/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

# =============================================================================
# ACTUATOR / MANAGEMENT CONFIGURATION
# =============================================================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  health:
    defaults:
      enabled: true
  info:
    env:
      enabled: true

# =============================================================================
# SPRING BOOT CONFIGURATION
# =============================================================================
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

# =============================================================================
# SHARED SECURITY CONFIGURATION
# =============================================================================
jwt:
  secret: ${JWT_SECRET:defaultSecretKey123456789012345678901234567890}
  expiration: 86400000 # 24 hours in milliseconds
