server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  kafka:
    bootstrap-servers: kafka:9092

  mail:
    host: ${PLATFORM_SMTP_HOST:smtp.hostinger.com}
    port: ${PLATFORM_SMTP_PORT:465}
    username: ${PLATFORM_SMTP_USERNAME:noreply@storeandsale.shop}
    password: ${PLATFORM_SMTP_PASSWORD:}

  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    com.fabricmanagement.notification: INFO
