server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

  mail:
    host: ${PLATFORM_SMTP_HOST:smtp.hostinger.com}
    port: ${PLATFORM_SMTP_PORT:465}
    username: ${PLATFORM_SMTP_USERNAME:info@storeandsale.shop}
    password: ${PLATFORM_SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          connectiontimeout: ${SMTP_CONNECTION_TIMEOUT:5000}
          timeout: ${SMTP_TIMEOUT:5000}
          writetimeout: ${SMTP_WRITE_TIMEOUT:5000}

  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    com.fabricmanagement.notification: INFO
