server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  kafka:
    bootstrap-servers: kafka:9092

  redis:
    host: redis
    port: 6379

logging:
  level:
    com.fabricmanagement.notification: INFO
