# =============================================================================
# FABRIC MANAGEMENT SYSTEM - AUTH SERVICE LOCAL DEVELOPMENT CONFIGURATION
# =============================================================================

spring:
  # ===========================================================================
  # DATABASE CONFIGURATION
  # ===========================================================================
  datasource:
    url: jdbc:postgresql://localhost:5433/fabric_management
    username: fabric_user
    password: local_dev_2024

  # ===========================================================================
  # FLYWAY CONFIGURATION
  # ===========================================================================
  flyway:
    table: flyway_schema_history_auth

  # ===========================================================================
  # CACHE CONFIGURATION
  # ===========================================================================
  data:
    redis:
      host: localhost
      port: 6379
      password: local_redis_pass

  # ===========================================================================
  # KAFKA CONFIGURATION
  # ===========================================================================
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# =============================================================================
# SERVER CONFIGURATION
# =============================================================================
server:
  port: ${AUTH_SERVICE_PORT:8085}

# =============================================================================
# AUTH SERVICE LOCAL CONFIGURATION
# =============================================================================
auth:
  jwt:
    secret: local-dev-jwt-secret-key-2024
    expiration: 86400000 # 24 hours
    refresh-expiration: 604800000 # 7 days

  password:
    min-length: ${AUTH_PASSWORD_MIN_LENGTH:8}
    require-special-chars: ${AUTH_PASSWORD_REQUIRE_SPECIAL:true}
    require-numbers: ${AUTH_PASSWORD_REQUIRE_NUMBERS:true}
    require-uppercase: ${AUTH_PASSWORD_REQUIRE_UPPERCASE:true}
    max-failed-attempts: ${AUTH_PASSWORD_MAX_FAILED_ATTEMPTS:5}

  session:
    timeout: ${AUTH_SESSION_TIMEOUT:1800} # 30 minutes
    max-sessions: ${AUTH_MAX_SESSIONS:5}

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
logging:
  level:
    com.fabricmanagement.auth: DEBUG
    org.springframework.security: DEBUG
