-- =============================================================================
-- V002 — CONSOLIDATED SEED DATA
-- Generated by consolidate_migrations.py
-- =============================================================================

-- ===================== FROM: V010__SEEDS.sql =====================
INSERT INTO common_tenant.common_tenant (
    id, uid, slug, name, billing_email, status, trial_ends_at, subscription_plan, settings,
    is_active, created_at, created_by, updated_at, updated_by, version
) VALUES (
    '00000000-0000-0000-0000-000000000000'::uuid,
    'SYS-000',
    'platform',
    'Platform (System)',
    NULL,
    'ACTIVE',
    NULL,
    NULL,
    '{"timezone":"UTC","locale":"en-US","currency":"USD","betaFeaturesEnabled":false,"aiEnabled":true,"emailNotificationsEnabled":true,"mfaRequired":false,"sessionTimeoutMinutes":480}'::jsonb,
    TRUE,
    CURRENT_TIMESTAMP,
    NULL,
    CURRENT_TIMESTAMP,
    NULL,
    0
)
ON CONFLICT (id) DO NOTHING;
DO $$
DECLARE
    platform_org_id UUID := gen_random_uuid();
    platform_role_id UUID := gen_random_uuid();
    platform_user_id UUID := gen_random_uuid();
    platform_contact_id UUID := gen_random_uuid();
    platform_auth_id UUID := gen_random_uuid();
    platform_admin_email VARCHAR := 'admin@fabricmanagement.com';
    platform_admin_password_hash VARCHAR := '$2a$10$X/q4m5.2jR6L9.P6s7hWueq7O.0.1.2.3.4.5.6.7.8.9.0.1.2.3'; -- Dummy bcrypt hash
BEGIN
    INSERT INTO common_company.common_organization (
        id, tenant_id, uid, name, tax_id, organization_type, is_active, created_at, updated_at, version
    ) VALUES (
        platform_org_id,
        '00000000-0000-0000-0000-000000000000',
        'SYS-PLATFORM-001',
        'Platform System',
        'PLATFORM-SYSTEM-001',
        'VERTICAL_MILL',
        TRUE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        0
    )
    ON CONFLICT (tenant_id, tax_id) DO NOTHING;
    INSERT INTO common_user.common_role (
        id, tenant_id, uid, role_name, role_code, description, role_scope, is_system_role, is_active, created_at, updated_at, version
    ) VALUES (
        platform_role_id,
        '00000000-0000-0000-0000-000000000000',
        'SYS-ROLE-0001',
        'Platform Administrator',
        'PLATFORM_ADMIN',
        'Full platform access',
        'INTERNAL',
        TRUE,
        TRUE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        0
    )
    ON CONFLICT (tenant_id, role_code) DO NOTHING;
    INSERT INTO common_user.common_user (
        id, tenant_id, uid, first_name, last_name, organization_id, role_id, user_type, is_active, created_at, updated_at, version
    ) VALUES (
        platform_user_id,
        '00000000-0000-0000-0000-000000000000',
        'SYS-USER-0001',
        'Platform',
        'Admin',
        platform_org_id,
        platform_role_id,
        'INTERNAL',
        TRUE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        0
    );
    INSERT INTO common_communication.common_contact (
        id, tenant_id, uid, contact_value, contact_type, is_verified, is_personal, is_active, created_at, updated_at, version
    ) VALUES (
        platform_contact_id,
        '00000000-0000-0000-0000-000000000000',
        'SYS-CONTACT-0001',
        platform_admin_email,
        'EMAIL',
        TRUE,
        TRUE,
        TRUE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        0
    );
    INSERT INTO common_user.common_user_contact (
        tenant_id, uid, user_id, contact_id, is_default, is_active, created_at, updated_at, version
    ) VALUES (
        '00000000-0000-0000-0000-000000000000',
        'SYS-USER-CONTACT-0001',
        platform_user_id,
        platform_contact_id,
        TRUE,
        TRUE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        0
    );
    INSERT INTO common_auth.common_auth_user (
        id, tenant_id, uid, user_id, password_hash, is_verified, is_active, created_at, updated_at, version
    ) VALUES (
        platform_auth_id,
        '00000000-0000-0000-0000-000000000000',
        'SYS-AUTH-0001',
        platform_user_id,
        platform_admin_password_hash,
        TRUE,
        TRUE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        0
    );
END $$;
INSERT INTO production.prod_fiber_category (tenant_id, uid, category_code, category_name, description, display_order) VALUES
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FCAT-00001', 'NATURAL_PLANT', 'Natural Plant', 'Cotton, Linen, Hemp, Jute, etc.', 1),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FCAT-00002', 'NATURAL_ANIMAL', 'Natural Animal', 'Wool, Silk, Cashmere, Alpaca, etc.', 2),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FCAT-00003', 'REGENERATED_CELLULOSIC', 'Regenerated Cellulosic', 'Viscose, Modal, Lyocell, Acetate, etc.', 3),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FCAT-00004', 'REGENERATED_PROTEIN', 'Regenerated Protein', 'Soy, Milk, Chitin, etc.', 4),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FCAT-00005', 'SYNTHETIC_POLYMER', 'Synthetic Polymer', 'Polyester, Nylon, Polypropylene, etc.', 5),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FCAT-00006', 'TECHNICAL_ADVANCED', 'Technical & Advanced', 'Carbon, Aramid, Ceramic, etc.', 6),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FCAT-00007', 'MINERAL', 'Mineral', 'Asbestos, Glass Fiber, etc.', 7),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FCAT-00008', 'MIXED_BLEND', 'Mixed Blend', 'Blends of different fiber origins', 8)
ON CONFLICT (uid) DO NOTHING;
INSERT INTO production.prod_product_attribute (tenant_id, uid, attribute_code, attribute_name, attribute_group, description, display_order) VALUES
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FATR-00001', 'DURABLE', 'Durable', 'PHYSICAL', 'Long-lasting fiber', 1),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FATR-00002', 'STRONG', 'Strong', 'PHYSICAL', 'High tensile strength', 2),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FATR-00003', 'ELASTIC', 'Elastic', 'PHYSICAL', 'High elongation', 3),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FATR-00004', 'MOISTURE_ABSORBENT', 'Moisture Absorbent', 'PHYSICAL', 'Good water absorption', 4),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FATR-00005', 'WICKING', 'Moisture Wicking', 'PHYSICAL', 'Transports moisture away', 5),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FATR-00006', 'HYDROPHOBIC', 'Hydrophobic', 'CHEMICAL', 'Water-repellent', 6),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FATR-00007', 'OLEOPHOBIC', 'Oleophobic', 'CHEMICAL', 'Oil-repellent', 7),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FATR-00008', 'FLAME_RESISTANT', 'Flame Resistant', 'CHEMICAL', 'Resists ignition', 8),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FATR-00009', 'UV_RESISTANT', 'UV Resistant', 'CHEMICAL', 'Resists UV degradation', 9),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FATR-00010', 'CHEMICAL_RESISTANT', 'Chemical Resistant', 'CHEMICAL', 'Resists chemical damage', 10),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FATR-00011', 'BIODEGRADABLE', 'Biodegradable', 'ENVIRONMENTAL', 'Naturally decomposes', 11),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FATR-00012', 'RECYCLABLE', 'Recyclable', 'ENVIRONMENTAL', 'Can be recycled', 12),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FATR-00013', 'RENEWABLE', 'Renewable', 'ENVIRONMENTAL', 'From renewable sources', 13),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FATR-00014', 'ORGANIC', 'Organic', 'ENVIRONMENTAL', 'Certified organic', 14),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FATR-00015', 'COMBED', 'Combed', 'PHYSICAL', 'Combed processing', 15),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FATR-00016', 'CARDED', 'Carded', 'PHYSICAL', 'Carded processing', 16),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FATR-00017', 'MERCERIZED', 'Mercerized', 'PHYSICAL', 'Mercerization treatment', 17),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FATR-00018', 'PRESHRUNK', 'Pre-Shrunk', 'PHYSICAL', 'Pre-shrinking treatment', 18),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FATR-00019', 'RECYCLED', 'Recycled', 'ENVIRONMENTAL', 'Contains recycled content', 19),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FATR-00020', 'BIOBASED', 'Bio-Based', 'ENVIRONMENTAL', 'Derived from biological sources', 20)
ON CONFLICT (uid) DO NOTHING;
INSERT INTO production.prod_fiber_certification (tenant_id, uid, certification_code, certification_name, certifying_body, description, display_order) VALUES
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FCER-00001', 'GOTS', 'Global Organic Textile Standard', 'Global Standard gGmbH', 'Organic textile certification', 1),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FCER-00002', 'BCI', 'Better Cotton Initiative', 'BCI', 'Sustainable cotton', 2),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FCER-00003', 'OEKO_TEX_100', 'OEKO-TEX Standard 100', 'OEKO-TEX', 'Harmful substance testing', 3),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FCER-00004', 'GRS', 'Global Recycled Standard', 'Textile Exchange', 'Recycled content', 4),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FCER-00005', 'FSC', 'Forest Stewardship Council', 'FSC', 'Responsible forest management', 5),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FCER-00006', 'OBCS', 'Organic Blended Content Standard', 'Textile Exchange', 'Organic blend certification', 6),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FCER-00007', 'OEKO_TEX_STEP', 'OEKO-TEX STeP', 'OEKO-TEX Association', 'Sustainable Textile Production', 7),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FCER-00008', 'BLUESIGN', 'bluesign', 'bluesign technologies ag', 'Chemical, water and energy management', 8),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FCER-00009', 'FAIR_TRADE', 'Fair Trade Certified', 'Fair Trade USA', 'Fair trade certification', 9),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FCER-00010', 'COTTON_USA', 'Cotton USA', 'Cotton Council International', 'USA origin and quality', 10),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FCER-00011', 'SUPIMA', 'Supima', 'Supima Association', 'American Pima cotton', 11),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FCER-00012', 'TENCEL', 'TENCEL™', 'Lenzing AG', 'Lenzing Lyocell/Modal', 12)
ON CONFLICT (uid) DO NOTHING;
INSERT INTO production.prod_fiber_iso_code (tenant_id, uid, iso_code, fiber_name, fiber_type, description, is_official_iso, display_order) VALUES
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00001', 'CO', 'Cotton', 'NATURAL_PLANT', 'Standard abbreviation for cotton', TRUE, 1),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00002', 'LI', 'Linen', 'NATURAL_PLANT', 'Linen / flax', TRUE, 2),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00003', 'HA', 'Hemp', 'NATURAL_PLANT', 'Hemp', TRUE, 3),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00004', 'JU', 'Jute', 'NATURAL_PLANT', 'Jute', TRUE, 4),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00005', 'RA', 'Ramie', 'NATURAL_PLANT', 'Bast fiber', TRUE, 5),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00006', 'BA', 'Bamboo', 'NATURAL_PLANT', 'Bamboo', TRUE, 6),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00007', 'CA', 'Coir', 'NATURAL_PLANT', 'Coconut husk', TRUE, 7),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00008', 'AB', 'Abaca', 'NATURAL_PLANT', 'Manila hemp', TRUE, 8),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00009', 'SI', 'Sisal', 'NATURAL_PLANT', 'Sisal fiber', TRUE, 9),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00010', 'PI', 'Pina', 'NATURAL_PLANT', 'Pineapple fiber', TRUE, 10),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00011', 'NE', 'Nettle', 'NATURAL_PLANT', 'Nettle fiber', TRUE, 11),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00012', 'KAP', 'Kapok', 'NATURAL_PLANT', 'Kapok', TRUE, 12),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00013', 'KEN', 'Kenaf', 'NATURAL_PLANT', 'Kenaf', TRUE, 13),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00014', 'ROS', 'Roselle', 'NATURAL_PLANT', 'Roselle', TRUE, 14),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00015', 'WO', 'Wool', 'NATURAL_ANIMAL', 'Wool', TRUE, 15),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00016', 'WS', 'Cashmere', 'NATURAL_ANIMAL', 'Fine goat hair', TRUE, 16),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00017', 'WM', 'Mohair', 'NATURAL_ANIMAL', 'Angora goat', TRUE, 17),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00018', 'WL', 'Alpaca', 'NATURAL_ANIMAL', 'Alpaca fiber', TRUE, 18),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00019', 'WP', 'Camel Hair', 'NATURAL_ANIMAL', 'Camel hair', TRUE, 19),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00020', 'WY', 'Yak Hair', 'NATURAL_ANIMAL', 'Yak hair', TRUE, 20),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00021', 'WG', 'Angora', 'NATURAL_ANIMAL', 'Rabbit fiber', TRUE, 21),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00022', 'SE', 'Silk', 'NATURAL_ANIMAL', 'Silk', TRUE, 22),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00023', 'WQ', 'Vicuna', 'NATURAL_ANIMAL', 'Vicuna', TRUE, 23),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00024', 'WZ', 'Llama', 'NATURAL_ANIMAL', 'Llama fiber', TRUE, 24),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00025', 'CV', 'Viscose', 'REGENERATED_CELLULOSIC', 'Viscose rayon', TRUE, 25),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00026', 'CMD', 'Modal', 'REGENERATED_CELLULOSIC', 'Modal', TRUE, 26),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00027', 'CLY', 'Lyocell', 'REGENERATED_CELLULOSIC', 'Lyocell (Tencel)', TRUE, 27),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00028', 'CUP', 'Cupro', 'REGENERATED_CELLULOSIC', 'Cupro', TRUE, 28),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00029', 'ACTA', 'Cellulose Acetate', 'REGENERATED_CELLULOSIC', 'Cellulose acetate', TRUE, 29),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00030', 'CTA', 'Triacetate', 'REGENERATED_CELLULOSIC', 'Triacetate', TRUE, 30),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00031', 'BBO', 'Bamboo Viscose', 'REGENERATED_CELLULOSIC', 'Bamboo viscose', TRUE, 31),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00032', 'COC', 'Co-Cupro', 'REGENERATED_CELLULOSIC', 'Cupro-lyocell', TRUE, 32),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00033', 'CBF', 'Banana Viscose', 'REGENERATED_CELLULOSIC', 'Banana viscose', TRUE, 33),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00034', 'SCC', 'SeaCell', 'REGENERATED_CELLULOSIC', 'SeaCell', TRUE, 34),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00035', 'COH', 'Hemp Viscose', 'REGENERATED_CELLULOSIC', 'Hemp viscose', TRUE, 35),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00036', 'PES', 'Polyester', 'SYNTHETIC_POLYMER', 'Polyester', TRUE, 36),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00037', 'PA', 'Polyamide (Nylon)', 'SYNTHETIC_POLYMER', 'Nylon', TRUE, 37),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00038', 'PAN', 'Polyacrylonitrile', 'SYNTHETIC_POLYMER', 'Acrylic', TRUE, 38),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00039', 'PP', 'Polypropylene', 'SYNTHETIC_POLYMER', 'Polypropylene', TRUE, 39),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00040', 'PE', 'Polyethylene', 'SYNTHETIC_POLYMER', 'Polyethylene', TRUE, 40),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00041', 'PU', 'Polyurethane', 'SYNTHETIC_POLYMER', 'Spandex, Elastane', TRUE, 41),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00042', 'PTFE', 'Polytetrafluoroethylene', 'SYNTHETIC_POLYMER', 'Teflon', TRUE, 42),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00043', 'PBI', 'Polybenzimidazole', 'SYNTHETIC_POLYMER', 'PBI', TRUE, 43),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00044', 'PPS', 'Polyphenylene Sulfide', 'SYNTHETIC_POLYMER', 'PPS', TRUE, 44),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00045', 'PVC', 'Polyvinyl Chloride', 'SYNTHETIC_POLYMER', 'PVC', TRUE, 45),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00046', 'AR', 'Aramid', 'SYNTHETIC_POLYMER', 'Aramid', TRUE, 46),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00047', 'PLA', 'Polylactic Acid', 'SYNTHETIC_POLYMER', 'PLA', TRUE, 47),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00048', 'CF', 'Carbon Fiber', 'SYNTHETIC_POLYMER', 'Carbon fiber', TRUE, 48),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00049', 'GF', 'Glass Fiber', 'SYNTHETIC_POLYMER', 'Glass fiber', TRUE, 49),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00050', 'BF', 'Basalt Fiber', 'SYNTHETIC_POLYMER', 'Basalt', TRUE, 50),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00051', 'MF', 'Metallic Fiber', 'SYNTHETIC_POLYMER', 'Metallic', TRUE, 51),
    ('00000000-0000-0000-0000-000000000000', 'SYS-000-FISO-00052', 'UHMWPE', 'Ultra-High-Molecular PE', 'SYNTHETIC_POLYMER', 'UHMWPE', TRUE, 52)
ON CONFLICT (uid) DO NOTHING;
INSERT INTO production.prod_yarn_category (tenant_id, uid, category_code, category_name, description, display_order)
VALUES
    ('00000000-0000-0000-0000-000000000000', 'SYS-YARN-CAT-001', 'SEWING', 'Sewing Yarn', 'Yarn used for sewing operations', 1),
    ('00000000-0000-0000-0000-000000000000', 'SYS-YARN-CAT-002', 'KNITTING', 'Knitting Yarn', 'Yarn used for knitting fabric', 2),
    ('00000000-0000-0000-0000-000000000000', 'SYS-YARN-CAT-003', 'WEAVING', 'Weaving Yarn', 'Yarn used for weaving fabric on loom', 3),
    ('00000000-0000-0000-0000-000000000000', 'SYS-YARN-CAT-004', 'EMBROIDERY', 'Embroidery Yarn', 'Decorative embroidery yarn', 4),
    ('00000000-0000-0000-0000-000000000000', 'SYS-YARN-CAT-005', 'SPECIALTY', 'Specialty Yarn', 'Special purpose yarn', 5)
ON CONFLICT (category_code) DO NOTHING;
INSERT INTO production.prod_yarn_attribute (tenant_id, uid, attribute_code, attribute_name, attribute_type, unit)
VALUES
    ('00000000-0000-0000-0000-000000000000', 'SYS-YARN-ATTR-001', 'COUNT', 'Yarn Count', 'PHYSICAL', 'Ne/Tex'),
    ('00000000-0000-0000-0000-000000000000', 'SYS-YARN-ATTR-002', 'TWIST', 'Twist per Meter', 'PHYSICAL', 'TPM'),
    ('00000000-0000-0000-0000-000000000000', 'SYS-YARN-ATTR-003', 'STRENGTH', 'Tensile Strength', 'MECHANICAL', 'cN/tex'),
    ('00000000-0000-0000-0000-000000000000', 'SYS-YARN-ATTR-004', 'ELONGATION', 'Elongation at Break', 'MECHANICAL', '%'),
    ('00000000-0000-0000-0000-000000000000', 'SYS-YARN-ATTR-005', 'HAIRINESS', 'Yarn Hairiness', 'PHYSICAL', 'H-value'),
    ('00000000-0000-0000-0000-000000000000', 'SYS-YARN-ATTR-006', 'EVENNESS', 'Yarn Evenness', 'QUALITY', 'CV%')
ON CONFLICT (attribute_code) DO NOTHING;
INSERT INTO production.prod_yarn_certification (tenant_id, uid, certification_code, certification_name, certifying_body)
VALUES
    ('00000000-0000-0000-0000-000000000000', 'SYS-YARN-CERT-001', 'GOTS', 'Global Organic Textile Standard', 'GOTS'),
    ('00000000-0000-0000-0000-000000000000', 'SYS-YARN-CERT-002', 'OEKO_TEX', 'Oeko-Tex Standard 100', 'OEKO-TEX'),
    ('00000000-0000-0000-0000-000000000000', 'SYS-YARN-CERT-003', 'GRS', 'Global Recycled Standard', 'Textile Exchange'),
    ('00000000-0000-0000-0000-000000000000', 'SYS-YARN-CERT-004', 'BSCI', 'Business Social Compliance Initiative', 'BSCI')
ON CONFLICT (certification_code) DO NOTHING;
INSERT INTO human.human_hr_policy_pack (id, tenant_id, uid, pack_code, pack_version, country_code, name, status, payload, inheritance_mode)
VALUES (gen_random_uuid(), '00000000-0000-0000-0000-000000000000'::uuid, 'SYS-HR-PACK-001', 'GLOBAL-BASE', 1, 'GLOBAL', 'Global Baseline', 'ACTIVE', '{}'::jsonb, 'FULL')
ON CONFLICT (tenant_id, pack_code, pack_version) DO NOTHING;
INSERT INTO human.human_hr_policy_pack (id, tenant_id, uid, pack_code, pack_version, country_code, name, status, payload, inheritance_mode, parent_pack_id, parent_pack_code, region_code)
SELECT gen_random_uuid(), '00000000-0000-0000-0000-000000000000'::uuid, 'SYS-HR-PACK-002', 'EU-BASELINE', 1, 'EU', 'EU Baseline', 'ACTIVE', '{}'::jsonb, 'PARTIAL',
       p.id, 'GLOBAL-BASE', 'EU'
FROM human.human_hr_policy_pack p
WHERE p.tenant_id = '00000000-0000-0000-0000-000000000000'::uuid AND p.pack_code = 'GLOBAL-BASE'
LIMIT 1
ON CONFLICT (tenant_id, pack_code, pack_version) DO NOTHING;
INSERT INTO common_communication.common_routing_config
(id, uid, tenant_id, country_code, primary_channel, fallback_channel, timeout_seconds, is_active, created_at, updated_at, version)
SELECT gen_random_uuid(), 'ROUTE-TR', NULL, 'TR', 'WHATSAPP', 'SMS', 15, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0
WHERE NOT EXISTS (SELECT 1 FROM common_communication.common_routing_config WHERE tenant_id IS NULL AND country_code = 'TR');
INSERT INTO common_communication.common_routing_config
(id, uid, tenant_id, country_code, primary_channel, fallback_channel, timeout_seconds, is_active, created_at, updated_at, version)
SELECT gen_random_uuid(), 'ROUTE-GB', NULL, 'GB', 'EMAIL', NULL, 0, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0
WHERE NOT EXISTS (SELECT 1 FROM common_communication.common_routing_config WHERE tenant_id IS NULL AND country_code = 'GB');

-- ===================== FROM: V20260317160000__faz4_costing_module.sql =====================
INSERT INTO costing.cost_item (id, tenant_id, code, name, scope, calculation_base, display_order)
VALUES
    (gen_random_uuid(), NULL, 'RAW_PRODUCT', 'Hammadde',       'GLOBAL', 'PER_KG',   1),
    (gen_random_uuid(), NULL, 'LABOR',        'İşçilik',         'GLOBAL', 'PER_HOUR',  2),
    (gen_random_uuid(), NULL, 'MACHINE',      'Makine/Ekipman', 'GLOBAL', 'PER_HOUR',  3),
    (gen_random_uuid(), NULL, 'ENERGY',       'Enerji',         'GLOBAL', 'PER_KG',   4),
    (gen_random_uuid(), NULL, 'OVERHEAD',     'Genel Gider',    'GLOBAL', 'PERCENTAGE',5),
    (gen_random_uuid(), NULL, 'LOGISTICS',    'Nakliye',        'GLOBAL', 'FIXED',     6),
    (gen_random_uuid(), NULL, 'QUALITY',      'Kalite Kontrol', 'GLOBAL', 'PER_UNIT',  7),
    (gen_random_uuid(), NULL, 'PACKAGING',    'Paketleme',      'GLOBAL', 'PER_UNIT',  8);
INSERT INTO costing.cost_item (id, tenant_id, code, name, scope, module_type, calculation_base, display_order)
VALUES
    (gen_random_uuid(), NULL, 'FIBER_SEPARATION', 'Elyaf Ayırma', 'MODULE_SPECIFIC', 'FIBER',   'PER_KG', 10),
    (gen_random_uuid(), NULL, 'FIBER_BALING',     'Balyalama',    'MODULE_SPECIFIC', 'FIBER',   'PER_KG', 11),
    (gen_random_uuid(), NULL, 'FIBER_MOISTURE',   'Nem Ayarı',    'MODULE_SPECIFIC', 'FIBER',   'PER_KG', 12),
    (gen_random_uuid(), NULL, 'YARN_TWIST',       'Büküm',        'MODULE_SPECIFIC', 'YARN',    'PER_KG', 13),
    (gen_random_uuid(), NULL, 'YARN_PLY',         'Katlama',      'MODULE_SPECIFIC', 'YARN',    'PER_KG', 14),
    (gen_random_uuid(), NULL, 'YARN_WINDING',     'Bobin Sarım', 'MODULE_SPECIFIC', 'YARN',    'PER_KG', 15),
    (gen_random_uuid(), NULL, 'FABRIC_WEAVING',   'Dokuma/Örgü',  'MODULE_SPECIFIC', 'FABRIC',  'PER_KG', 16),
    (gen_random_uuid(), NULL, 'FABRIC_SIZING',    'Haşıl',        'MODULE_SPECIFIC', 'FABRIC',  'PER_KG', 17),
    (gen_random_uuid(), NULL, 'FABRIC_WARPING',   'Çözgü',        'MODULE_SPECIFIC', 'FABRIC',  'PER_KG', 18),
    (gen_random_uuid(), NULL, 'DYE_CHEMICAL',     'Boya Kimyasalı','MODULE_SPECIFIC','DYE',    'PER_KG', 19),
    (gen_random_uuid(), NULL, 'DYE_WATER',        'Su Tüketimi',   'MODULE_SPECIFIC', 'DYE',    'PER_KG', 20),
    (gen_random_uuid(), NULL, 'DYE_FINISHING',    'Apre',         'MODULE_SPECIFIC', 'DYE',    'PER_KG', 21);

-- ===================== FROM: V20260319100000__faz7_i18n_notification_hub.sql =====================
INSERT INTO i18n.supported_locale (id, tenant_id, code, name, is_rtl)
VALUES
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000001', 'TR', 'Türkçe', FALSE),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000001', 'EN', 'English', FALSE),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000001', 'DE', 'Deutsch', FALSE),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000001', 'FR', 'Français', FALSE),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000001', 'AR', 'العربية', TRUE)
ON CONFLICT (code) DO NOTHING;

-- ===================== FROM: V20260319110000__faz7_notification_seeds.sql =====================
  INSERT INTO i18n.translation_key (id, tenant_id, key_code, module, default_value, description)
  VALUES
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.batch_qc_failed.title', 'NOTIFICATION',
     'QC Failed: Batch {batchCode}', 'BatchQcFailed event title'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.batch_qc_failed.body', 'NOTIFICATION',
     'Batch {batchCode} failed quality control. Immediate action required.', 'BatchQcFailed event body'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.work_order_pending_approval.title', 'NOTIFICATION',
     'Approval Required: {workOrderNumber}', 'WorkOrderPendingApproval title'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.work_order_pending_approval.body', 'NOTIFICATION',
     'Work order {workOrderNumber} is waiting for your approval.', 'WorkOrderPendingApproval body'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.goods_receipt_confirmed.title', 'NOTIFICATION',
     'Goods Received: {receiptNumber}', 'GoodsReceiptConfirmed title'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.goods_receipt_confirmed.body', 'NOTIFICATION',
     'Receipt {receiptNumber} confirmed. {itemCount} item(s) added to stock.', 'GoodsReceiptConfirmed body'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.task_blocked.title', 'NOTIFICATION',
     'Task Blocked: {taskTitle}', 'TaskBlocked title'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.task_blocked.body', 'NOTIFICATION',
     'Task "{taskTitle}" has been blocked. Reason: {reason}', 'TaskBlocked body')
  ON CONFLICT (key_code) DO NOTHING;
  INSERT INTO i18n.translation_value (id, tenant_id, translation_key_id, locale, value, is_override)
  SELECT gen_random_uuid(), '00000000-0000-0000-0000-000000000000', tk.id, 'TR',
    CASE tk.key_code
      WHEN 'notification.batch_qc_failed.title'                  THEN 'KK Başarısız: Parti {batchCode}'
      WHEN 'notification.batch_qc_failed.body'                   THEN '{batchCode} partisi kalite kontrolünü geçemedi. Acil müdahale gerekiyor.'
      WHEN 'notification.work_order_pending_approval.title'       THEN 'Onay Gerekiyor: {workOrderNumber}'
      WHEN 'notification.work_order_pending_approval.body'        THEN '{workOrderNumber} numaralı iş emri onayınızı bekliyor.'
      WHEN 'notification.goods_receipt_confirmed.title'           THEN 'Mal Teslim Alındı: {receiptNumber}'
      WHEN 'notification.goods_receipt_confirmed.body'            THEN '{receiptNumber} girişi onaylandı. {itemCount} kalem stoğa eklendi.'
      WHEN 'notification.task_blocked.title'                      THEN 'Görev Engellendi: {taskTitle}'
      WHEN 'notification.task_blocked.body'                       THEN '"{taskTitle}" görevi engellendi. Neden: {reason}'
    END,
    FALSE
  FROM i18n.translation_key tk
  WHERE tk.key_code IN (
    'notification.batch_qc_failed.title', 'notification.batch_qc_failed.body',
    'notification.work_order_pending_approval.title', 'notification.work_order_pending_approval.body',
    'notification.goods_receipt_confirmed.title', 'notification.goods_receipt_confirmed.body',
    'notification.task_blocked.title', 'notification.task_blocked.body'
  )
  ON CONFLICT (translation_key_id, locale, tenant_id) DO NOTHING;

-- ===================== FROM: V20260319120000__faz7_notification_translations_extended.sql =====================
  INSERT INTO i18n.translation_key (id, tenant_id, key_code, module, default_value, description)
  VALUES
    -- WorkOrderPendingApproval
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.work_order_pending_approval.title', 'NOTIFICATION',
     'Approval Required: {workOrderNumber}', 'WorkOrderPendingApproval title'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.work_order_pending_approval.body', 'NOTIFICATION',
     'Work order {workOrderNumber} is waiting for your approval.', 'WorkOrderPendingApproval body'),

    -- ApprovalPending
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.approval_pending.title', 'NOTIFICATION',
     'Approval Required: {entityCode}', 'ApprovalPending title'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.approval_pending.body', 'NOTIFICATION',
     '{entityType} {entityCode} requires your approval.', 'ApprovalPending body'),

    -- ApprovalRejected
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.approval_rejected.title', 'NOTIFICATION',
     'Rejected: {entityCode}', 'ApprovalRejected title'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.approval_rejected.body', 'NOTIFICATION',
     'Your request {entityCode} was rejected. Reason: {rejectionReason}', 'ApprovalRejected body'),

    -- MinStockAlert
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.min_stock_alert.title', 'NOTIFICATION',
     'Low Stock: {productCode}', 'MinStockAlert title'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.min_stock_alert.body', 'NOTIFICATION',
     'Product {productCode} - {productName} is below minimum stock level. Current: {currentStock} {unit}, Min: {minimumStock} {unit}.', 'MinStockAlert body'),

    -- PoDeliveryLate
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.po_delivery_late.title', 'NOTIFICATION',
     'Delivery Overdue: {poNumber}', 'PoDeliveryLate title'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.po_delivery_late.body', 'NOTIFICATION',
     'Purchase order {poNumber} from {supplierName} is {lateDays} day(s) overdue.', 'PoDeliveryLate body'),

    -- RfqDeadlineApproaching
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.rfq_deadline_approaching.title', 'NOTIFICATION',
     'RFQ Deadline Soon: {rfqNumber}', 'RfqDeadlineApproaching title'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.rfq_deadline_approaching.body', 'NOTIFICATION',
     'RFQ {rfqNumber} deadline is in {hoursRemaining} hour(s). Please review pending responses.', 'RfqDeadlineApproaching body'),

    -- RfqNoResponse
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.rfq_no_response.title', 'NOTIFICATION',
     'No Response: {supplierName}', 'RfqNoResponse title'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.rfq_no_response.body', 'NOTIFICATION',
     'Supplier {supplierName} has not responded to RFQ {rfqNumber}.', 'RfqNoResponse body'),

    -- =========================================================
    -- Translation Keys — NORMAL eventler
    -- =========================================================

    -- WorkOrderApproved
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.work_order_approved.title', 'NOTIFICATION',
     'Approved: {workOrderNumber}', 'WorkOrderApproved title'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.work_order_approved.body', 'NOTIFICATION',
     'Work order {workOrderNumber} has been approved. Production can begin.', 'WorkOrderApproved body'),

    -- ApprovalApproved
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.approval_approved.title', 'NOTIFICATION',
     'Approved: {entityCode}', 'ApprovalApproved title'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.approval_approved.body', 'NOTIFICATION',
     'Your request {entityCode} has been approved.', 'ApprovalApproved body'),

    -- BatchQcPending
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.batch_qc_pending.title', 'NOTIFICATION',
     'QC Required: Batch {batchCode}', 'BatchQcPending title'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.batch_qc_pending.body', 'NOTIFICATION',
     'Batch {batchCode} is ready for quality control inspection.', 'BatchQcPending body'),

    -- GoodsReceiptConfirmed
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.goods_receipt_confirmed.title', 'NOTIFICATION',
     'Goods Received: {receiptNumber}', 'GoodsReceiptConfirmed title'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.goods_receipt_confirmed.body', 'NOTIFICATION',
     'Receipt {receiptNumber} confirmed. {itemCount} item(s) added to stock.', 'GoodsReceiptConfirmed body'),

    -- PoConfirmed
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.po_confirmed.title', 'NOTIFICATION',
     'PO Confirmed: {poNumber}', 'PoConfirmed title'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.po_confirmed.body', 'NOTIFICATION',
     'Purchase order {poNumber} has been confirmed by supplier.', 'PoConfirmed body'),

    -- PoPartiallyReceived
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.po_partially_received.title', 'NOTIFICATION',
     'Partial Delivery: {poNumber}', 'PoPartiallyReceived title'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.po_partially_received.body', 'NOTIFICATION',
     '{receivedItemCount} of {totalItemCount} items received for PO {poNumber}.', 'PoPartiallyReceived body'),

    -- ReturnRateExceeded (CRITICAL)
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.return_rate_exceeded.title', 'NOTIFICATION',
     'CRITICAL: Return Rate Exceeded — {supplierName}', 'ReturnRateExceeded title'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.return_rate_exceeded.body', 'NOTIFICATION',
     'Supplier {supplierName} return rate is {returnRate}% (threshold: {thresholdRate}%) over {periodDays} days.', 'ReturnRateExceeded body')

  ON CONFLICT (key_code) DO NOTHING;
  INSERT INTO i18n.translation_value (id, tenant_id, translation_key_id, locale, value, is_override)
  SELECT gen_random_uuid(), '00000000-0000-0000-0000-000000000000', tk.id, 'TR',
    CASE tk.key_code
      -- WorkOrderPendingApproval
      WHEN 'notification.work_order_pending_approval.title'  THEN 'Onay Gerekiyor: {workOrderNumber}'
      WHEN 'notification.work_order_pending_approval.body'   THEN '{workOrderNumber} numaralı iş emri onayınızı bekliyor.'
      -- ApprovalPending
      WHEN 'notification.approval_pending.title'             THEN 'Onay Gerekiyor: {entityCode}'
      WHEN 'notification.approval_pending.body'              THEN '{entityType} {entityCode} onayınızı bekliyor.'
      -- ApprovalRejected
      WHEN 'notification.approval_rejected.title'            THEN 'Reddedildi: {entityCode}'
      WHEN 'notification.approval_rejected.body'             THEN '{entityCode} talebiniz reddedildi. Neden: {rejectionReason}'
      -- ApprovalApproved
      WHEN 'notification.approval_approved.title'            THEN 'Onaylandı: {entityCode}'
      WHEN 'notification.approval_approved.body'             THEN '{entityCode} talebiniz onaylandı.'
      -- MinStockAlert
      WHEN 'notification.min_stock_alert.title'              THEN 'Düşük Stok: {productCode}'
      WHEN 'notification.min_stock_alert.body'               THEN '{productCode} - {productName} malzemesi minimum stok seviyesinin altında. Mevcut: {currentStock} {unit}, Min: {minimumStock} {unit}.'
      -- PoDeliveryLate
      WHEN 'notification.po_delivery_late.title'             THEN 'Teslimat Gecikti: {poNumber}'
      WHEN 'notification.po_delivery_late.body'              THEN '{supplierName} tedarikçisinden {poNumber} numaralı PO {lateDays} gün gecikmeli.'
      -- RfqDeadlineApproaching
      WHEN 'notification.rfq_deadline_approaching.title'     THEN 'RFQ Deadline Yaklaşıyor: {rfqNumber}'
      WHEN 'notification.rfq_deadline_approaching.body'      THEN '{rfqNumber} RFQ''nin deadline''ına {hoursRemaining} saat kaldı. Bekleyen yanıtları inceleyin.'
      -- RfqNoResponse
      WHEN 'notification.rfq_no_response.title'              THEN 'Yanıt Yok: {supplierName}'
      WHEN 'notification.rfq_no_response.body'               THEN '{supplierName} tedarikçisi {rfqNumber} RFQ için yanıt vermedi.'
      -- WorkOrderApproved
      WHEN 'notification.work_order_approved.title'          THEN 'Onaylandı: {workOrderNumber}'
      WHEN 'notification.work_order_approved.body'           THEN '{workOrderNumber} numaralı iş emri onaylandı. Üretim başlayabilir.'
      -- BatchQcPending
      WHEN 'notification.batch_qc_pending.title'             THEN 'KK Gerekiyor: Parti {batchCode}'
      WHEN 'notification.batch_qc_pending.body'              THEN '{batchCode} partisi kalite kontrol incelemesine hazır.'
      -- GoodsReceiptConfirmed
      WHEN 'notification.goods_receipt_confirmed.title'      THEN 'Mal Teslim Alındı: {receiptNumber}'
      WHEN 'notification.goods_receipt_confirmed.body'       THEN '{receiptNumber} girişi onaylandı. {itemCount} kalem stoğa eklendi.'
      -- PoConfirmed
      WHEN 'notification.po_confirmed.title'                 THEN 'PO Onaylandı: {poNumber}'
      WHEN 'notification.po_confirmed.body'                  THEN '{poNumber} numaralı satın alma siparişi tedarikçi tarafından onaylandı.'
      -- PoPartiallyReceived
      WHEN 'notification.po_partially_received.title'        THEN 'Kısmi Teslim: {poNumber}'
      WHEN 'notification.po_partially_received.body'         THEN '{poNumber} PO için {receivedItemCount}/{totalItemCount} kalem teslim alındı.'
      -- ReturnRateExceeded
      WHEN 'notification.return_rate_exceeded.title'         THEN 'KRİTİK: İade Oranı Aşıldı — {supplierName}'
      WHEN 'notification.return_rate_exceeded.body'          THEN '{supplierName} tedarikçisinin iade oranı {periodDays} günde %{returnRate} (eşik: %{thresholdRate}).'
    END,
    FALSE
  FROM i18n.translation_key tk
  WHERE tk.key_code IN (
    'notification.work_order_pending_approval.title', 'notification.work_order_pending_approval.body',
    'notification.approval_pending.title', 'notification.approval_pending.body',
    'notification.approval_rejected.title', 'notification.approval_rejected.body',
    'notification.approval_approved.title', 'notification.approval_approved.body',
    'notification.min_stock_alert.title', 'notification.min_stock_alert.body',
    'notification.po_delivery_late.title', 'notification.po_delivery_late.body',
    'notification.rfq_deadline_approaching.title', 'notification.rfq_deadline_approaching.body',
    'notification.rfq_no_response.title', 'notification.rfq_no_response.body',
    'notification.work_order_approved.title', 'notification.work_order_approved.body',
    'notification.batch_qc_pending.title', 'notification.batch_qc_pending.body',
    'notification.goods_receipt_confirmed.title', 'notification.goods_receipt_confirmed.body',
    'notification.po_confirmed.title', 'notification.po_confirmed.body',
    'notification.po_partially_received.title', 'notification.po_partially_received.body',
    'notification.return_rate_exceeded.title', 'notification.return_rate_exceeded.body'
  )
  ON CONFLICT (translation_key_id, locale, tenant_id) DO NOTHING;

-- ===================== FROM: V20260319130000__faz7_notification_template_seeds.sql =====================
  INSERT INTO notification.notification_template
    (id, tenant_id, event_type, channel, title_key, body_key, importance, delivery_type)
  VALUES
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'BATCH_QC_FAILED', 'IN_APP',
     'notification.batch_qc_failed.title', 'notification.batch_qc_failed.body',
     'CRITICAL', 'INSTANT'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'BATCH_QC_FAILED', 'EMAIL',
     'notification.batch_qc_failed.title', 'notification.batch_qc_failed.body',
     'CRITICAL', 'INSTANT'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'BATCH_QC_FAILED', 'PUSH',
     'notification.batch_qc_failed.title', 'notification.batch_qc_failed.body',
     'CRITICAL', 'INSTANT')
  ON CONFLICT (tenant_id, event_type, channel) DO NOTHING;
  INSERT INTO notification.notification_template
    (id, tenant_id, event_type, channel, title_key, body_key, importance, delivery_type)
  VALUES
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'RETURN_RATE_EXCEEDED', 'IN_APP',
     'notification.return_rate_exceeded.title', 'notification.return_rate_exceeded.body',
     'CRITICAL', 'INSTANT'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'RETURN_RATE_EXCEEDED', 'EMAIL',
     'notification.return_rate_exceeded.title', 'notification.return_rate_exceeded.body',
     'CRITICAL', 'INSTANT'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'RETURN_RATE_EXCEEDED', 'PUSH',
     'notification.return_rate_exceeded.title', 'notification.return_rate_exceeded.body',
     'CRITICAL', 'INSTANT')
  ON CONFLICT (tenant_id, event_type, channel) DO NOTHING;
  INSERT INTO notification.notification_template
    (id, tenant_id, event_type, channel, title_key, body_key, importance, delivery_type)
  VALUES
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'WORK_ORDER_PENDING_APPROVAL', 'IN_APP',
     'notification.work_order_pending_approval.title', 'notification.work_order_pending_approval.body',
     'HIGH', 'INSTANT'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'WORK_ORDER_PENDING_APPROVAL', 'EMAIL',
     'notification.work_order_pending_approval.title', 'notification.work_order_pending_approval.body',
     'HIGH', 'INSTANT')
  ON CONFLICT (tenant_id, event_type, channel) DO NOTHING;
  INSERT INTO notification.notification_template
    (id, tenant_id, event_type, channel, title_key, body_key, importance, delivery_type)
  VALUES
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'APPROVAL_PENDING', 'IN_APP',
     'notification.approval_pending.title', 'notification.approval_pending.body',
     'HIGH', 'INSTANT'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'APPROVAL_PENDING', 'EMAIL',
     'notification.approval_pending.title', 'notification.approval_pending.body',
     'HIGH', 'INSTANT')
  ON CONFLICT (tenant_id, event_type, channel) DO NOTHING;
  INSERT INTO notification.notification_template
    (id, tenant_id, event_type, channel, title_key, body_key, importance, delivery_type)
  VALUES
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'APPROVAL_REJECTED', 'IN_APP',
     'notification.approval_rejected.title', 'notification.approval_rejected.body',
     'HIGH', 'INSTANT'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'APPROVAL_REJECTED', 'EMAIL',
     'notification.approval_rejected.title', 'notification.approval_rejected.body',
     'HIGH', 'INSTANT')
  ON CONFLICT (tenant_id, event_type, channel) DO NOTHING;
  INSERT INTO notification.notification_template
    (id, tenant_id, event_type, channel, title_key, body_key, importance, delivery_type)
  VALUES
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'MIN_STOCK_ALERT', 'IN_APP',
     'notification.min_stock_alert.title', 'notification.min_stock_alert.body',
     'HIGH', 'INSTANT'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'MIN_STOCK_ALERT', 'EMAIL',
     'notification.min_stock_alert.title', 'notification.min_stock_alert.body',
     'HIGH', 'INSTANT')
  ON CONFLICT (tenant_id, event_type, channel) DO NOTHING;
  INSERT INTO notification.notification_template
    (id, tenant_id, event_type, channel, title_key, body_key, importance, delivery_type)
  VALUES
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'PO_DELIVERY_LATE', 'IN_APP',
     'notification.po_delivery_late.title', 'notification.po_delivery_late.body',
     'HIGH', 'INSTANT'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'PO_DELIVERY_LATE', 'EMAIL',
     'notification.po_delivery_late.title', 'notification.po_delivery_late.body',
     'HIGH', 'INSTANT')
  ON CONFLICT (tenant_id, event_type, channel) DO NOTHING;
  INSERT INTO notification.notification_template
    (id, tenant_id, event_type, channel, title_key, body_key, importance, delivery_type)
  VALUES
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'RFQ_DEADLINE_APPROACHING', 'IN_APP',
     'notification.rfq_deadline_approaching.title', 'notification.rfq_deadline_approaching.body',
     'HIGH', 'INSTANT'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'RFQ_DEADLINE_APPROACHING', 'EMAIL',
     'notification.rfq_deadline_approaching.title', 'notification.rfq_deadline_approaching.body',
     'HIGH', 'INSTANT')
  ON CONFLICT (tenant_id, event_type, channel) DO NOTHING;
  INSERT INTO notification.notification_template
    (id, tenant_id, event_type, channel, title_key, body_key, importance, delivery_type)
  VALUES
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'RFQ_NO_RESPONSE', 'IN_APP',
     'notification.rfq_no_response.title', 'notification.rfq_no_response.body',
     'HIGH', 'INSTANT'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'RFQ_NO_RESPONSE', 'EMAIL',
     'notification.rfq_no_response.title', 'notification.rfq_no_response.body',
     'HIGH', 'INSTANT')
  ON CONFLICT (tenant_id, event_type, channel) DO NOTHING;
  INSERT INTO notification.notification_template
    (id, tenant_id, event_type, channel, title_key, body_key, importance, delivery_type)
  VALUES
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'WORK_ORDER_APPROVED', 'IN_APP',
     'notification.work_order_approved.title', 'notification.work_order_approved.body',
     'NORMAL', 'INSTANT')
  ON CONFLICT (tenant_id, event_type, channel) DO NOTHING;
  INSERT INTO notification.notification_template
    (id, tenant_id, event_type, channel, title_key, body_key, importance, delivery_type)
  VALUES
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'APPROVAL_APPROVED', 'IN_APP',
     'notification.approval_approved.title', 'notification.approval_approved.body',
     'NORMAL', 'INSTANT')
  ON CONFLICT (tenant_id, event_type, channel) DO NOTHING;
  INSERT INTO notification.notification_template
    (id, tenant_id, event_type, channel, title_key, body_key, importance, delivery_type)
  VALUES
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'BATCH_QC_PENDING', 'IN_APP',
     'notification.batch_qc_pending.title', 'notification.batch_qc_pending.body',
     'NORMAL', 'INSTANT')
  ON CONFLICT (tenant_id, event_type, channel) DO NOTHING;
  INSERT INTO notification.notification_template
    (id, tenant_id, event_type, channel, title_key, body_key, importance, delivery_type)
  VALUES
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'GOODS_RECEIPT_CONFIRMED', 'IN_APP',
     'notification.goods_receipt_confirmed.title', 'notification.goods_receipt_confirmed.body',
     'NORMAL', 'INSTANT')
  ON CONFLICT (tenant_id, event_type, channel) DO NOTHING;
  INSERT INTO notification.notification_template
    (id, tenant_id, event_type, channel, title_key, body_key, importance, delivery_type)
  VALUES
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'PO_CONFIRMED', 'IN_APP',
     'notification.po_confirmed.title', 'notification.po_confirmed.body',
     'NORMAL', 'INSTANT')
  ON CONFLICT (tenant_id, event_type, channel) DO NOTHING;
  INSERT INTO notification.notification_template
    (id, tenant_id, event_type, channel, title_key, body_key, importance, delivery_type)
  VALUES
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'PO_PARTIALLY_RECEIVED', 'IN_APP',
     'notification.po_partially_received.title', 'notification.po_partially_received.body',
     'NORMAL', 'INSTANT')
  ON CONFLICT (tenant_id, event_type, channel) DO NOTHING;

-- ===================== FROM: V20260320110000__faz8_flowboard_seeds.sql =====================
    INSERT INTO flowboard.task_label (id, tenant_id, name, color, icon, board_id)
    VALUES
        -- URGENT — +15 priorityScore bonus
        (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'URGENT',           '#E74C3C', '🔴', NULL),
        -- VIP_CLIENT — +20 priorityScore bonus
        (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'VIP_CLIENT',       '#9B59B6', '⭐', NULL),
        -- FIRST_ORDER — +10 priorityScore bonus
        (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'FIRST_ORDER',      '#3498DB', '🆕', NULL),
        -- SAMPLE — +0 priorityScore bonus
        (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'SAMPLE',           '#2ECC71', '🧪', NULL),
        -- REWORK — +5 priorityScore bonus
        (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'REWORK',           '#E67E22', '🔄', NULL),
        -- WAITING_EXTERNAL — +0 priorityScore bonus
        (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'WAITING_EXTERNAL', '#95A5A6', '⏳', NULL)
    ON CONFLICT (tenant_id, name, board_id) DO NOTHING;

-- ===================== FROM: V20260320120000__faz8_2_smart_task_generator.sql =====================
INSERT INTO flowboard.task_template (name, tenant_id, event_type, title_template, task_type, default_priority, default_assignee_role, estimated_hours)
VALUES ('Auto Template', '00000000-0000-0000-0000-000000000000', 'SalesOrderConfirmed', 'Planlama — {salesOrder.orderNumber}', 'PLANNING', 'HIGH', 'MANAGER', 2.0)
ON CONFLICT DO NOTHING;
INSERT INTO flowboard.task_template (name, tenant_id, event_type, title_template, task_type, default_priority, default_assignee_role, estimated_hours)
VALUES ('Auto Template', '00000000-0000-0000-0000-000000000000', 'WorkOrderPendingApproval', 'WO onay — {workOrder.orderNumber}', 'APPROVAL', 'HIGH', 'MANAGER', 0.5)
ON CONFLICT DO NOTHING;
INSERT INTO flowboard.task_template (name, tenant_id, event_type, title_template, task_type, default_priority, default_assignee_role, estimated_hours)
VALUES ('Auto Template', '00000000-0000-0000-0000-000000000000', 'WorkOrderApproved', 'Üretim başlat — {workOrder.orderNumber}', 'PRODUCTION', 'MEDIUM', 'DEPARTMENT_ADMIN', 8.0)
ON CONFLICT DO NOTHING;
INSERT INTO flowboard.task_template (name, tenant_id, event_type, title_template, task_type, default_priority, default_assignee_role, estimated_hours)
VALUES ('Auto Template', '00000000-0000-0000-0000-000000000000', 'BatchQcPending', 'QC kontrol — {batch.batchNumber}', 'QUALITY', 'MEDIUM', 'DEPARTMENT_ADMIN', 1.0)
ON CONFLICT DO NOTHING;
INSERT INTO flowboard.task_template (name, tenant_id, event_type, title_template, task_type, default_priority, default_assignee_role, estimated_hours, auto_labels)
VALUES ('Auto Template', '00000000-0000-0000-0000-000000000000', 'BatchQcFailed', 'QC başarısız — yeniden işlem — {batch.batchNumber}', 'QUALITY', 'CRITICAL', 'DEPARTMENT_ADMIN', 4.0, '["URGENT","REWORK"]')
ON CONFLICT DO NOTHING;
INSERT INTO flowboard.task_template (name, tenant_id, event_type, title_template, task_type, default_priority, default_assignee_role, estimated_hours)
VALUES ('Auto Template', '00000000-0000-0000-0000-000000000000', 'GoodsReceiptConfirmed', 'Depo yerleştirme — {goodsReceipt.receiptNumber}', 'WAREHOUSE', 'MEDIUM', 'DEPARTMENT_ADMIN', 1.5)
ON CONFLICT DO NOTHING;
INSERT INTO flowboard.task_template (name, tenant_id, event_type, title_template, task_type, default_priority, default_assignee_role, estimated_hours)
VALUES ('Auto Template', '00000000-0000-0000-0000-000000000000', 'SalesOrderInWarehouse', 'Sevkiyat hazırla — {salesOrder.orderNumber}', 'SHIPMENT', 'HIGH', 'DEPARTMENT_ADMIN', 2.0)
ON CONFLICT DO NOTHING;
INSERT INTO flowboard.task_template (name, tenant_id, event_type, title_template, task_type, default_priority, default_assignee_role, estimated_hours)
VALUES ('Auto Template', '00000000-0000-0000-0000-000000000000', 'RecipeAssignmentNeeded', 'Manuel recipe seç — {salesOrderLine.productDesc}', 'RECIPE_ASSIGNMENT', 'HIGH', 'MANAGER', 1.0)
ON CONFLICT DO NOTHING;
INSERT INTO flowboard.task_template (name, tenant_id, event_type, title_template, task_type, default_priority, default_assignee_role, estimated_hours, auto_labels)
VALUES ('Auto Template', '00000000-0000-0000-0000-000000000000', 'MinStockAlert', 'Stok kritik — {product.name} temin et', 'PROCUREMENT', 'HIGH', 'MANAGER', 2.0, '["URGENT"]')
ON CONFLICT DO NOTHING;
INSERT INTO flowboard.task_template (name, tenant_id, event_type, title_template, task_type, default_priority, default_assignee_role, estimated_hours)
VALUES ('Auto Template', '00000000-0000-0000-0000-000000000000', 'PoDeliveryLate', 'PO gecikti — {purchaseOrder.poNumber} takip et', 'PROCUREMENT', 'HIGH', 'MANAGER', 1.0)
ON CONFLICT DO NOTHING;
INSERT INTO flowboard.task_template (name, tenant_id, event_type, title_template, task_type, default_priority, default_assignee_role, estimated_hours)
VALUES ('Auto Template', '00000000-0000-0000-0000-000000000000', 'CostVarianceDetected', 'Maliyet sapması — {costCalculation.referenceNumber}', 'COSTING', 'MEDIUM', 'MANAGER', 1.5)
ON CONFLICT DO NOTHING;
INSERT INTO flowboard.task_template (name, tenant_id, event_type, title_template, task_type, default_priority, default_assignee_role, estimated_hours)
VALUES ('Auto Template', '00000000-0000-0000-0000-000000000000', 'ReturnRateExceeded', 'İade oranı aşıldı — {tradingPartner.companyName}', 'RETURN', 'HIGH', 'MANAGER', 2.0)
ON CONFLICT DO NOTHING;
INSERT INTO flowboard.task_template (name, tenant_id, event_type, title_template, task_type, default_priority, default_assignee_role, estimated_hours)
VALUES ('Auto Template', '00000000-0000-0000-0000-000000000000', 'ApprovalPending', 'Onay bekliyor — {approvalRequest.referenceNumber}', 'APPROVAL', 'HIGH', 'MANAGER', 0.5)
ON CONFLICT DO NOTHING;
INSERT INTO flowboard.task_template (name, tenant_id, event_type, title_template, task_type, default_priority, default_assignee_role, estimated_hours)
VALUES ('Auto Template', '00000000-0000-0000-0000-000000000000', 'UserPromotionReady', 'Kullanıcı yükseltme — {user.displayName}', 'APPROVAL', 'MEDIUM', 'MANAGER', 0.5)
ON CONFLICT DO NOTHING;
INSERT INTO flowboard.task_template (name, tenant_id, event_type, title_template, task_type, default_priority, default_assignee_role, estimated_hours)
VALUES ('Auto Template', '00000000-0000-0000-0000-000000000000', 'SupplierLicenseExpiringSoon', 'Lisans yenileme — {tradingPartner.companyName}', 'GENERAL', 'MEDIUM', 'MANAGER', 1.0)
ON CONFLICT DO NOTHING;
INSERT INTO flowboard.automation_rule (tenant_id, name, trigger_type, trigger_config, condition_config, action_type, action_config)
VALUES ('00000000-0000-0000-0000-000000000000',
        'QC bitti → depo görevi aç',
        'STATUS_CHANGED',
        '{"fromStatus": "IN_PROGRESS", "toStatus": "DONE"}',
        '{"taskType": "QUALITY"}',
        'CREATE_TASK',
        '{"taskType": "WAREHOUSE", "titleTemplate": "Depo: {task.title}"}')
ON CONFLICT DO NOTHING;
INSERT INTO flowboard.automation_rule (tenant_id, name, trigger_type, trigger_config, condition_config, action_type, action_config)
VALUES ('00000000-0000-0000-0000-000000000000',
        'Kritik deadline yaklaşıyor',
        'DEADLINE_APPROACHING',
        '{"hoursBeforeDeadline": 24}',
        '{"priority": ["HIGH", "CRITICAL"]}',
        'NOTIFY_MANAGER',
        '{"message": "Task deadline 24 saat kaldı: {task.title}"}')
ON CONFLICT DO NOTHING;
INSERT INTO flowboard.automation_rule (tenant_id, name, trigger_type, trigger_config, condition_config, action_type, action_config)
VALUES ('00000000-0000-0000-0000-000000000000',
        'WIP limiti aşıldı bildirimi',
        'WIP_EXCEEDED',
        '{}',
        NULL,
        'NOTIFY_MANAGER',
        '{"message": "WIP limiti aşıldı! Kullanıcı: {user.displayName}"}')
ON CONFLICT DO NOTHING;
INSERT INTO flowboard.automation_rule (tenant_id, name, trigger_type, trigger_config, condition_config, action_type, action_config)
VALUES ('00000000-0000-0000-0000-000000000000',
        'Büyük task BLOCKED oldu',
        'STATUS_CHANGED',
        '{"toStatus": "BLOCKED"}',
        '{"estimatedHoursGte": 8}',
        'ESCALATE',
        '{"escalateTo": "DEPARTMENT_ADMIN"}')
ON CONFLICT DO NOTHING;
INSERT INTO flowboard.automation_rule (tenant_id, name, trigger_type, trigger_config, condition_config, action_type, action_config)
VALUES ('00000000-0000-0000-0000-000000000000',
        'VIP etiket → öncelik +20',
        'LABEL_ADDED',
        '{"labelName": "VIP_CLIENT"}',
        NULL,
        'UPDATE_PRIORITY',
        '{"priorityBonus": 20}')
ON CONFLICT DO NOTHING;
INSERT INTO flowboard.automation_rule (tenant_id, name, trigger_type, trigger_config, condition_config, action_type, action_config)
VALUES ('00000000-0000-0000-0000-000000000000',
        'Checklist tamamlandı → IN_REVIEW',
        'CHECKLIST_COMPLETED',
        '{}',
        NULL,
        'CHANGE_STATUS',
        '{"newStatus": "IN_REVIEW"}')
ON CONFLICT DO NOTHING;
INSERT INTO flowboard.automation_rule (tenant_id, name, trigger_type, trigger_config, condition_config, action_type, action_config)
VALUES ('00000000-0000-0000-0000-000000000000',
        'Süre tahmini %150 aşıldı',
        'TIMER_EXCEEDED',
        '{"thresholdPercent": 150}',
        NULL,
        'ADD_LABEL',
        '{"labelName": "URGENT"}')
ON CONFLICT DO NOTHING;
INSERT INTO flowboard.automation_rule (tenant_id, name, trigger_type, trigger_config, condition_config, action_type, action_config)
VALUES ('00000000-0000-0000-0000-000000000000',
        '2 saat atanmamış task',
        'TASK_UNASSIGNED_TOO_LONG',
        '{"maxHoursUnassigned": 2}',
        NULL,
        'NOTIFY_MANAGER',
        '{"message": "Task 2 saattir atanmadı: {task.title}"}')
ON CONFLICT DO NOTHING;

-- ===================== FROM: V20260322130000__faz8_4_seeds.sql =====================
        INSERT INTO flowboard.dashboard_config 
        (id, tenant_id, user_id, name, is_default, layout_jsonb)
        VALUES 
        ('11111111-1111-1111-1111-111111111111', '00000000-0000-0000-0000-000000000000', (SELECT id FROM common_user.common_user WHERE uid = 'SYS-USER-0001' LIMIT 1), 'System Manager Dashboard', true, 
         '{"breakpoints": {"lg": 1200, "md": 996}, "layouts": {"lg": [{"i": "widget-1", "x": 0, "y": 0, "w": 4, "h": 2}]}}'::jsonb);
        INSERT INTO flowboard.dashboard_widget (id, tenant_id, dashboard_id, widget_type, title, display_order, config_jsonb) VALUES
        (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', '11111111-1111-1111-1111-111111111111', 'TASK_COUNT', 'Total Open Tasks', 1, '{}'),
        (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', '11111111-1111-1111-1111-111111111111', 'OVERDUE_TASKS', 'Critical Overdue Tasks', 2, '{"severity": "CRITICAL"}'),
        (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', '11111111-1111-1111-1111-111111111111', 'WORKLOAD_CHART', 'Team Workload', 3, '{}'),
        (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', '11111111-1111-1111-1111-111111111111', 'LEADERBOARD', 'Top Performers', 4, '{"limit": 5}'),
        (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', '11111111-1111-1111-1111-111111111111', 'MY_TASKS', 'My Assigned Tasks', 5, '{}'),
        (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', '11111111-1111-1111-1111-111111111111', 'RECENT_ACTIVITY', 'Recent Board Activity', 6, '{"limit": 10}'),
        (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', '11111111-1111-1111-1111-111111111111', 'TEAM_PERFORMANCE', 'Weekly Team Stats', 7, '{}'),
        (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', '11111111-1111-1111-1111-111111111111', 'BOTTLENECKS', 'Process Bottlenecks', 8, '{}'),
        (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', '11111111-1111-1111-1111-111111111111', 'TIME_TRACKING_SUMMARY', 'Timesheet Overview', 9, '{}');
        INSERT INTO flowboard.board (id, tenant_id, uid, name, board_type)
        VALUES ('22222222-2222-2222-2222-222222222222', '00000000-0000-0000-0000-000000000000', 'SYS-BOARD-001', 'Global Default Board', 'GLOBAL')
        ON CONFLICT DO NOTHING;

        INSERT INTO flowboard.recurring_task_template
        (id, tenant_id, board_id, title, description, task_type, priority, frequency, is_active, next_trigger_at)
        VALUES
        (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', (SELECT id FROM flowboard.board LIMIT 1), 'Daily Standup Prep', 'Prepare notes for daily standup', 'GENERAL', 'MEDIUM', 'DAILY', true, NOW() + INTERVAL '1 day'),
        (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', (SELECT id FROM flowboard.board LIMIT 1), 'Weekly Equipment Calibration', 'Calibrate production machines', 'MAINTENANCE', 'HIGH', 'WEEKLY', true, NOW() + INTERVAL '7 days'),
        (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', (SELECT id FROM flowboard.board LIMIT 1), 'Monthly Inventory Count', 'Count the main warehouse inventory', 'STOCK_COUNT', 'CRITICAL', 'MONTHLY', true, NOW() + INTERVAL '30 days'),
        (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', (SELECT id FROM flowboard.board LIMIT 1), 'Quarterly Quality Audit', 'Conduct internal ISO quality audit', 'QUALITY', 'HIGH', 'QUARTERLY', true, NOW() + INTERVAL '90 days'),
        (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', (SELECT id FROM flowboard.board LIMIT 1), 'Annual Performance Reviews', 'Annual employee review cycle', 'GENERAL', 'MEDIUM', 'YEARLY', true, NOW() + INTERVAL '365 days'),
        (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', (SELECT id FROM flowboard.board LIMIT 1), 'Post-Production Safety Check', 'Check site after production run', 'GENERAL', 'MEDIUM', 'ON_COMPLETION', true, null);

-- ===================== FROM: V20260329102000__seed_work_order_approval_policy.sql =====================
INSERT INTO common_approval.approval_policy (
    id, tenant_id, uid, entity_type, required_for_level, approver_role, promotion_threshold, is_active, created_by
)
SELECT 
    gen_random_uuid(),
    t.id,
    'SYS-000-PO-' || UPPER(SUBSTRING(CAST(gen_random_uuid() AS VARCHAR), 1, 8)),
    'WORK_ORDER',
    'PROBATION',
    'MANAGER',
    10,
    true,
    NULL
FROM common_tenant.common_tenant t
WHERE NOT EXISTS (
    SELECT 1 FROM common_approval.approval_policy p 
    WHERE p.tenant_id = t.id AND p.entity_type = 'WORK_ORDER' AND p.required_for_level = 'PROBATION'
);

-- ===================== FROM: V20260402150000__flowboard_automation_alert_template.sql =====================
  INSERT INTO notification.notification_template
    (id, tenant_id, event_type, channel, title_key, body_key, importance, delivery_type)
  VALUES
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000',
     'AUTOMATION_ALERT', 'IN_APP',
     'notification.automation_alert.title', 'notification.automation_alert.body',
     'NORMAL', 'INSTANT')
  ON CONFLICT (tenant_id, event_type, channel) DO NOTHING;
  INSERT INTO i18n.translation_key (id, tenant_id, key_code, module, default_value, description)
  VALUES
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.automation_alert.title', 'NOTIFICATION',
     'Automation Alert!', 'AutomationAlertRequested title'),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'notification.automation_alert.body', 'NOTIFICATION',
     '{message}', 'AutomationAlertRequested body')
  ON CONFLICT (key_code) DO NOTHING;
  INSERT INTO i18n.translation_value (id, tenant_id, translation_key_id, locale, value, is_override)
  SELECT gen_random_uuid(), '00000000-0000-0000-0000-000000000000', tk.id, 'TR',
    CASE tk.key_code
      WHEN 'notification.automation_alert.title' THEN 'Otomasyon Uyarısı!'
      WHEN 'notification.automation_alert.body'  THEN '{message}'
    END,
    FALSE
  FROM i18n.translation_key tk
  WHERE tk.key_code IN (
    'notification.automation_alert.title', 'notification.automation_alert.body'
  )
  ON CONFLICT (translation_key_id, locale, tenant_id) DO NOTHING;
