name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Check code compilation
        run: mvn clean compile -pl service/user-service,service/contact-service

      - name: Run unit tests
        run: mvn test -pl service/user-service,service/contact-service

      - name: Check test results
        if: always()
        run: |
          echo "Test Summary:"
          find . -name "TEST-*.xml" -exec echo "Found test results: {}" \;