# =============================================================================
# COMPANY SERVICE - LOCAL ENVIRONMENT OVERRIDES
# =============================================================================
# Contains only local development-specific configuration overrides

# =============================================================================
# DEVELOPMENT OVERRIDES
# =============================================================================
spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update # Allow schema updates in local development
    show-sql: true # Enable SQL logging for debugging
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# =============================================================================
# LOCAL COMPANY SERVICE OVERRIDES
# =============================================================================
company:
  validation:
    tax-id:
      enabled: false # Disable tax validation in local development
      provider: mock
  address:
    validation:
      enabled: false # Disable address validation in local development
  document:
    upload:
      storage-path: /tmp/uploads/companies # Local temp directory for development

# =============================================================================
# DEVELOPMENT LOGGING
# =============================================================================
logging:
  level:
    com.fabricmanagement.company: DEBUG
